### ISSUE TITLE
Build out Birth Certs email templates

### ISSUE THREAD

**Issue by jessicamarcus** [CityOfBoston/digital#176]
- Request has been received
- Request processed / invoice
- Addt'l information request
- Information request reminder
- Request cancelled

**Comment by fionawhim** [comment]
Rachel will draft the content for these emails

**Comment by rachelbraun** [comment]
**Request processed / invoice**
Title: YOUR BIRTH CERTIFICATE ORDER IS ON ITS WAY

Content: We’ve processed your order and charged your card. Your order is being shipped via USPS to the shipping address you provided.

Include Order Info and Total below that text.

**Comment by fionawhim** [comment]
@rachelbraun Here’s the expired email so far:

<img width="710" alt="screen shot 2019-02-19 at 3 02 22 pm" src="https://user-images.githubusercontent.com/260837/53043850-6f8fb980-3457-11e9-9074-d7cee6f261b0.png">

**Comment by rachelbraun** [comment]
- [x] Request has been received
- [x] Request processed / invoice

Scratch:
* Addt'l information request
* Information request reminder

_Moving forward: If Registry requests additional support here, we'll add a link for upload. If they need support on top of that, we'll set up email framework from database to send email request for ID and/or supporting documents._

**Request canceled email**
YOUR ORDER HAS BEEN CANCELED

We have canceled your birth certificate request and removed the hold from your card. Your card will not be charged.

If you would like to place a new order, visit [registry.boston.gov/birth](url).
