### ISSUE TITLE
Update commissions search app to work with D8

### ISSUE THREAD

**Issue by zweishar** [CityOfBoston/digital#222]
The commissions search app is designed to ingest settings that are created by Drupal. In Drupal 7, those settings lived at `window.Drupal.settings.bos_commissions_search.bos_commissions_search_graphql_endpoint`
`window.Drupal.settings.bos_commissions_search.bos_commissions_search_graphql_api_key`

That path is different in D8. It is now:     `window.drupalSettings.bos_commissions.bos_commissions_search.graphql_endpoint`
`window.drupalSettings.bos_commissions.bos_commissions_search.api_key`

Ideally we could push an update to this app that would allow it to function in both D7 + D8.

I assigned @jessicamarcus and @mmcgowanBOS as I think you're best suited to take this over.

**Comment by reillyzlab** [comment]
Needs to be looked into to see if this needs to happen.

Particularly if it's going to break the search.

**Comment by jimafisk** [comment]
Example: https://www.boston.gov/civic-engagement/boards-and-commissions

**Comment by reillyzlab** [comment]
Resolved so closing
