### ISSUE TITLE
UI for ID upload step in questions flow

### ISSUE THREAD

**Issue by jessicamarcus** [CityOfBoston/digital#264]
Component to enable a user to upload images and documents for identification verification. 

This component will be used in the questions flow `verifyInformation` step, as well as a freestanding page; when the Registry manually requests id verification from a user for an existing order, this page is where that user is directed.

**Waiting on:**
- [ ] detailed instructions for the user
- [x] visual design for interface
- [x] allowed file types for documents

**Functional requirements:**
- user must submit front and back images of their id
- user can add addt’l supporting documents
- user can review their images before submitting
- user can use their device’s camera to take a photo of documents, if possible

**Comment by fionawhim** [comment]
Saving these to the DB will be a separate bug.

**Comment by fionawhim** [comment]
![registry-certs digital-staging boston gov_birth_step verifyidentification](https://user-images.githubusercontent.com/260837/52215254-a9f73500-2861-11e9-9bbf-62f7eca7e12b.png)

^^^ Based on this page, adding front / back upload regions, supporting documents list

**Comment by carolinestj** [comment]
@jessicamarcus latest update to ID flow, let me know what assets you need! 
<img width="913" alt="screen shot 2019-02-07 at 11 02 23 am" src="https://user-images.githubusercontent.com/22770827/52426524-23925b80-2acc-11e9-832b-e30c2876d3f3.png">
