### ISSUE TITLE
"Client" landing page

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/digital#269]
When user selects “client” for the question ”how are you related?”, this information is displayed and the request flow ends.

**Comment by jessicamarcus** [comment]
See visual: https://xd.adobe.com/view/2cbd3d29-bf5c-4243-4a87-4144feae1db7-5a8c/screen/ae32c8c3-1bad-44c5-a542-d6fbaf96492e/7B

**Comment by rachelbraun** [comment]
If user selects, 'Someone Else' then 'Client', then move to this blurb and end process.

### Visual
![7b](https://user-images.githubusercontent.com/35377030/52010518-bc5d2180-24a3-11e9-9fd6-06c4594108ea.png)

### Language

Title:
You must complete this process in person or through the mail.

Content:
If you are a legal representative making a request for a client, you need these items to get a record:

a letter on letterhead stating you legally represent the person for whom you are requesting a record
a photocopy of your ID (state-issued ID, driver's license, or government-issued ID), and
a copy of your BAR card (must be in good standing and not expired).

You must complete this process in person at Boston City Hall or through the mail. In person, the cost per request is $12. We take cash, credit or debit cards, checks, or money orders. By mail, the cost per request is $14. We accept checks or money orders payable to the City of Boston.

You can find more information online at boston.gov/birth

Please note: if you are a legal representative and making a mail request, we will only return the record to your address.
