### ISSUE TITLE
Issue w/Cancel and Start Over Link

### ISSUE THREAD

**Issue by rachelbraun** [CityOfBoston/digital#326]
On the Review Your Request page, clicking the "Cancel and start over" link takes the user back one page to Step 4 (Parent Information) instead of Step 1.

Add'l note:
That "Cancel and start over" link takes the user back one page to Step 4 (Parent Information) but all the information is cleared.

Right now, users can go from Step 4 through to Payment without filling out all the required information.

**Comment by fionawhim** [comment]
Can we also revisit the UI on this? I'm not a fan of having the two different links.

**Comment by fionawhim** [comment]
For reference:

<img width="847" alt="screen shot 2019-02-21 at 11 39 30 am" src="https://user-images.githubusercontent.com/260837/53185650-6e809880-35cd-11e9-94c8-c713ca6a60da.png">


Maybe "cancel and start over" could be small and centered and below everything?
