### ISSUE TITLE
Investigate restricted record request moving to fulfillment w/o ID attached

### ISSUE THREAD

**Issue by rachelbraun** [CityOfBoston/digital#370]
User selected parents were married but request went through to fulfillment w/no ID attached.

**Comment by rachelbraun** [comment]
<img width="800" alt="Screen Shot 2019-03-14 at 11 17 57 AM" src="https://user-images.githubusercontent.com/35377030/54368790-293f0c00-464b-11e9-9ee4-82d388343dc7.png">

**Comment by fionawhim** [comment]
I think I know what this is, or at least one cause.

We don't require image uploads to be _successful_ to proceed, just to happen.
