### ISSUE TITLE
Edge Browser Icon Bug 

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/digital#386]
Birth Certs

Edge browser on Windows 10:

![image](https://user-images.githubusercontent.com/33470951/54633046-bc19e500-4a55-11e9-9fa3-4894480ea7cb.png)

**Comment by BrutiAnteneh** [comment]
![image](https://user-images.githubusercontent.com/33470951/54634696-1c5e5600-4a59-11e9-89ca-59d129c446a8.png)

**Comment by reillyzlab** [comment]
@maxbahar can you check whether this is still an issue
