### ISSUE TITLE
Add alert to payment page when missing info

### ISSUE THREAD

**Issue by rachelbraun** [CityOfBoston/digital#406]
A few users are getting stuck on the payment page, thinking they can't move forward - when they haven't filled out all of the Credit/Debit Card info.

Consider making it so that when grey button is clicked, missing info (like CVC code greyed out text) turns red.

**Comment by rachelbraun** [comment]
<img width="497" alt="Screen Shot 2019-03-28 at 4 41 27 PM" src="https://user-images.githubusercontent.com/35377030/55194250-78bf2500-517f-11e9-956a-ef1cc89cf2df.png">

**Comment by andrebtlima** [comment]
The field for Cardholder Name turns red when left blank but the same needs to be applied to the Card Number field.
