### ISSUE TITLE
Access Boston: Add application group management to the portal

### ISSUE THREAD

**Issue by jessicamarcus** [CityOfBoston/digital#466]
see: https://github.com/CityOfBoston/iam/issues/644

The IIQ user experience for admins is not ideal for adding/removing groups for an end user, so we are adding this functionality to the [access-boston](../tree/develop/services-js/access-boston) portal.

- in the portal under Support Tools, a “Manage Groups” link will be present for specific app owners
- an app owner can search for an end user by name or ID
- an app owner can add/remove the groups that end user belongs to
- an app owner can see a list of all groups they may manage
- an app owner can see the membership of a given group

**Manage groups view**
- list of available groups => _Group membership view_
- “search for user” field => _End user view_

**Group membership view**
- list of available groups
- list of members for a selected group
- clickable list of users => _End user view_

**End user view**
- user’s name and ID
- all available groups with checkboxes to indicate user’s membership
- Next => _Confirmation view_

**Confirmation view**
- user’s name and ID
- list of current groups end user is member of
- Make changes => _End user view_
- Submit => **end of flow** => _Manage groups view_

We should bypass IIQ and use LDAP directly as per @samkatta - see http://ldapjs.org/ library

**Comment by jessicamarcus** [comment]
Questions:
- [ ] Should Group membership view also show a list of a given group’s admins?
- [ ] What is the desired experience for search results? Inline suggestions autocomplete?

**Comment by jessicamarcus** [comment]
Design ticket: https://github.com/CityOfBoston/creative-team-workflow/issues/1306

**Comment by reillyzlab** [comment]
Completed
