### ISSUE TITLE
Registry: Allow people to put a birth date range

### ISSUE THREAD

**Issue by sarahgreisdorf** [CityOfBoston/digital#475]
Similar to marriage in case people don't know the date

**Comment by reillyzlab** [comment]
This is the page that is being referred to on marriage application.

![Screen Shot 2020-10-08 at 11 53 22 AM](https://user-images.githubusercontent.com/20731897/95483132-7df45700-0954-11eb-9d18-6b7ed648e3ee.png)

https://registry.boston.gov/marriage?step=dateOfMarriage

**Comment by stephaniemar** [comment]
We need to Touch base with Patty on this
