### ISSUE TITLE
Registry: Add option to allow multiple alternative spellings on birth application

### ISSUE THREAD

**Issue by sarahgreisdorf** [CityOfBoston/digital#478]
Add multiple options like in marriage

**Comment by stephaniemar** [comment]
Ask Patty

**Comment by stephaniemar** [comment]
In Birth request --- Change spelling to Spellings- Plural-  in the Alternative Spelling field

**Comment by stephaniemar** [comment]
Adding this to the following ticket https://github.com/CityOfBoston/digital/issues/661
