### ISSUE TITLE
react-fleet: Menu toolbar formatting issue

### ISSUE THREAD

**Issue by max-zjh-the** [CityOfBoston/digital#482]
On death, birth, and marriage, the Menu sidebar is formatted differently from other pages on Boston.gov. Instead of the contents of "Places" and "Government" being on a secondary page, it is now shown on the main menu.

Marriage cert online form page:
![image](https://user-images.githubusercontent.com/42783424/62575066-e7b43500-b867-11e9-8169-1bcb057c013b.png)

Career center page:
![image](https://user-images.githubusercontent.com/42783424/62575063-e5ea7180-b867-11e9-8193-36117ad74744.png)

**Comment by jessicamarcus** [comment]
Ah, this is a digital webapps issue, not specific to Registry. I’m going to return to this issue.

**Comment by stephaniemar** [comment]
Side bar is in different code bases.
