### ISSUE TITLE
Registry: 'Verify Email' field on review order page

### ISSUE THREAD

**Issue by max-zjh-the** [CityOfBoston/digital#487]
On birth certs and marriage certs, add a 'verify email' field and in-line edit to the review page. Possibly make it similar to the 'Shipping Address' verification field.

![image](https://user-images.githubusercontent.com/42783424/62576530-11229000-b86b-11e9-97fc-df19b9e4505d.png)

**Comment by jessicamarcus** [comment]
I’ll add a “contact information” section in the style of the other two that will show the name and phone number provided, alongside the email address.
