### ISSUE TITLE
Registry: Marriage Certificates Analytics

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#495]
Please implement to track:

- [x] General pageviews
- [ ] Who is ordering?
- [ ] Conversion of how far they get in the app? Do they drop off at a certain page? Do they hit submit at the end?
- [ ] Track whether user added something in the comment box.
- [ ] See if people looked at their order details on the shipping page
- [x] Track whether people are opening the Apostille details.
- [ ] Track is people are uploading ID or not. Note if people are drag/dropping or uploading using interface.
- [ ] Track same [event] actions as the rest of the registry suite.
- [ ] Ecommerce, if easy. If not, then we'll track through payment provider.

**Comment by jessicamarcus** [comment]
If we can track ecommerce through Stripe, I think we ought to.

@mmcgowanBOS can you look through this list of requirements then walk me through what I need to provide in order to meet them? This has become a significant blocker for me. 😞

**Comment by mmcgowanBOS** [comment]
@jessicamarcus, just sent a Google Calendar invite to discuss. I've gone ahead and addressed a few of the already.

**Comment by mmcgowanBOS** [comment]
1. Pageviews
    - Tracking with default GA 

2. Who is ordering?
    - Matt to look further into (possible JS solution through even handler click reading radio button val OR get REACT state through code base change)

3. Conversions and user flow
   - Data can be taken from Stripe and also User Flows in default GA

4. User commented in box?
   - Going to check if comment box is not NULL or empty string before "continue" button is clicked.

5. Apostille clicks?
  - Matt Already setup will Publish in Tag Manager 

6. Check if upload ID
  - Matt Going to see if we can check for a FORM value change on this specific step before user hits continue button (Dropzone library)

7. Same Events across all Life Suite Web Apps
  - PM to audit and find what currently is being tracked, we then can cross check against all 

8. Ecommerce
  - Reilly to confirm if we want to Marriage to show up in Enhanced E-commerce section of GA?

**Comment by reillyzlab** [comment]
Closing because we haven't been asked for additional analytics.
