### ISSUE TITLE
Access Boston: Analytics

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#506]
Reilly add context for analytics later

**Comment by reillyzlab** [comment]
- [ ] Stats for group management (@mmcgowanBOS and @phillipbentonkelly to make recommendations on what to do here]
* Main things to accomplish is the 'impressions'

- [ ] Change analytics to be tag manager rather than native google analytics

Set this up as tags within analytics:
- [x] **Number of visits per icon so we know how to best order them based on usage.** Also allows us to level set with 'app owners'. Anecdotally, app owners say they had a massive increase in use since their icons appeared on the website -- we do not have pre-analytics to track this. Also trying to use this to gauge how many people go to access boston first and then go out to the apps, rather than the direct links the apps themselves.
- [x] Tracking open and completion (did people get all the way through/hit submit) for self service functionalities, which right now include: 
- Forgot password?
- Change my password
- Manage my devices
- Manage delegates

- [ ] Security has also been working with Analytics to get dashboarding of multiple data sets/info into Tableau. Look into connecting this data into tableau.

**Comment by reillyzlab** [comment]
Should have been working. @mmcgowanBOS and @phillipbentonkelly revisiting this.

**Comment by reillyzlab** [comment]
Applications portion is done and can be seen in Behavior > Events > Event Label @gretchen-grozier

**Comment by reillyzlab** [comment]
@mmcgowanBOS or @phillipbentonkelly can you advise where to find: 
Tracking open and completion (did people get all the way through/hit submit) for self service functionalities, which right now include:

**Comment by mmcgowanBOS** [comment]
Sure, as mentioned to Gretchen earlier (maybe over the summer), you can view the main "Site Contnet->Pages" in Google Analytics to measure which pages people are clicking and how far they get through specific use cases. See link below.

https://analytics.google.com/analytics/web/#/report/content-pages/a99773468w197176079p192129454/

Assigning back to Gretchen.

**Comment by gretchen-grozier** [comment]
I am only seeing functions in the Site Content/All Pages (change password, register).  There seem to be 15 things.  What we want to track is clicks on ESS | Boston Maps | Civis etc....

![image](https://user-images.githubusercontent.com/44211968/69733135-d8007b00-10fa-11ea-9899-a69d2fc45583.png)

assigning back to @mmcgowanBOS
