### ISSUE TITLE
Access Boston: Set up to externally access data

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#507]
Determined on 9/11 that we are able to have data for the Access Boston Portal. Previously had open question about ability to access.

Proofed it out, but will need to validate.

**Comment by reillyzlab** [comment]
@phillipbentonkelly to finish this up as well as provide the Security team with documentation

**Comment by phillipbentonkelly** [comment]
Closing this issue; We have access to the LDAP Dev Environment through our VPC on AWS.
