### ISSUE TITLE
Access Boston: Add link to portal for group management

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#510]
Add link to Access Boston portal.

@gretchen-grozier can you provide the following:

- [x] What the verbiage should be for the link?

- [x] Where this link should fall on the portal?

**Comment by gretchen-grozier** [comment]
@reillyzlab Updated Portal Content sheet for this new functionality.
https://docs.google.com/spreadsheets/d/1OiH2HBLE55X8MzGaB7H9VC_a2WpQQcjV4-eyNpJGTPY/edit?usp=sharing

The link should say 'Group Management'  (shown only to those members of the SG_AB_GRPMGMT group/a specific subset of app owners) and it should be in the 'Support Tools' section

**Comment by reillyzlab** [comment]
- [x] Dev Environment
- [x] Staging Environment
- [ ] Production Environment

**Comment by phillipbentonkelly** [comment]
The link is visible on Dev now, takes into account if the SAML response says you belong to a management group, if not you won't see it. Deploying to Staging tonight/early tomorrow morning, so am marking that (tentatively) done.

**Comment by gretchen-grozier** [comment]
@phillipbentonkelly Please don't move to Staging until we have it okayed in DEV.

**Comment by reillyzlab** [comment]
Completed.
