### ISSUE TITLE
Access Boston: 'Alert' message

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#511]
Access Boston has an 'alert' system that allows a developer to hard code a message in. 

This was used during launch and there is 'expectation' that this could/would be used for 

Given that Access Boston is _not_ a content management system we need to figure out requirements, how to solve for this, and how to communicate back out to stakeholders.

**Comment by jfalvey** [comment]
Dependency on HR / Hub conversations that are with CFO

**Comment by reillyzlab** [comment]
As discussed in person we will not be immediately implementing anything here.

We need to discuss this on a larger scale, because the Access Boston site is not a content management system and most likely shouldn't be controlling/maintaining/displaying these messages.
