### ISSUE TITLE
Access Boston: Add AgilePoint to Portal

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#514]
Add icon to each environment: 
Development Environment: https://boston-d-app01.nxone.com
Staging / Testing Environment: https://boston-s-app.nxone.com
Production Environment: https://boston.nxone.com

Group: SG_AB_AGILEPOINT

See email from Gretchen for icon to use

Name with icon: Boston Forms

Location on portal: Try to populate to the icon to the right of 'The Hub'

**Comment by gretchen-grozier** [comment]
@jessicamarcus @phillipbentonkelly Please not this work needs to be complete by EOD on Friday, October 4th.  I'll drop whatever to do quick round of testing (before we push to PROD)

**Comment by gretchen-grozier** [comment]
that should be note, not not -- as in please note this work....

**Comment by gretchen-grozier** [comment]
@jessicamarcus @phillipbentonkelly 
Name with icon should be 'Agilepoint' not 'Boston Forms' per Bryan at 11:30 on 10/4

**Comment by reillyzlab** [comment]
Completed
