### ISSUE TITLE
Access Boston: Add Proofpoint to portal

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#516]
Most likely go live 10/9 - Greg to provide more details on 10/8.
Time: TBD

Name: TBD

Icon: See Gretchen email to digital

Security group: SG_AB_PROOFPOINT

**Comment by phillipbentonkelly** [comment]
Hi @gretchen-grozier, do we have the remaining details for this or are we still waiting on Greg. I got the icon from one of the emails and uploaded it already.

**Comment by gretchen-grozier** [comment]
@gmccarthy83 this is Greg's release..... happy to help if you all need me to coordinate something.  But I don't have details currently.  @phillipbentonkelly

**Comment by gmccarthy83** [comment]
Name: Security Awareness

Please move to Dev and Test today. Should be visible to all users EXCEPT Boston Public Schools (same as AgilePoint).

Move to PROD tomorrow (10/9 @ 10am).

**Comment by phillipbentonkelly** [comment]
I updated dev && test/staging with the new entry.

**Comment by reillyzlab** [comment]
To @gmccarthy83 to test and confirm

**Comment by gretchen-grozier** [comment]
@reillyzlab @phillipbentonkelly @gmccarthy83 Dinesh tested with a full compliment of users (various affiliations) as has confirmed it's good to go.

**Comment by gretchen-grozier** [comment]
@reillyzlab I cannot assign this over to ...Phil?  But Digital can deploy to Prod at 10am tomorrow!

**Comment by reillyzlab** [comment]
Added
