### ISSUE TITLE
Update Access-Boston App Icon URLs

### ISSUE THREAD

**Issue by phillipbentonkelly** [CityOfBoston/digital#520]
Change the url for icons in the config file from relative paths to absolute paths pointing to the new Assets directory build out of patterns by Dave. Since the config file for apps (apps.yaml) already lives outside our Digital repo it makes no sense to have do a build/deploy just to add a new icon. I copied the current icons over to the [https://assets.boston.gov](https://assets.boston.gov/icons/accessboston/agilepoint.svg), so all that needs to be done is update the URL paths in the config files for dev/test/prod.

[AgilePoint Icon](https://assets.boston.gov/icons/accessboston/agilepoint.svg)

**Comment by phillipbentonkelly** [comment]
Changed the icon urls on the config files for DEV/TEST to point to https://assets.boston.gov/ instead of https://access.boston.gov/.

Test Criteria: Check all icons are working working with different group access. Check that the icon URLs point to https://assets.boston.gov/.

**Comment by phillipbentonkelly** [comment]
Update: This is now on DEV and Test, @gretchen-grozier I assigned the ticket to you, didn't want to just go assigned it to Dinesh.

**Comment by gretchen-grozier** [comment]
@reillyzlab I have no idea what any of this means, could digital set up a meeting about what changes are being made and why with the IAM team pls?  Is this the thing that let's IAM make changes to add new icons, etc?

**Comment by reillyzlab** [comment]
This test was to change the URL/location that the icons were populating from (i.e. where they were hosted) to match where all digital icons are/should be populating.

I was able to test this on my own user profile on test and it appears to be working, but we wanted someone else to QA as well, ideally with a user role that has access to all possible icons. 

All Access Boston website icons should be coming from assets.boston.gov/...

Someone can test this by: 
1. Going to Access Boston test environment/website and logging in and once logged in...
2. Right clicking anywhere on the page until a pop up screen appears.
3. On the pop up screen clicking 'inspect'
![Screen Shot 2020-01-08 at 4 09 49 PM](https://user-images.githubusercontent.com/20731897/72016229-67886600-3231-11ea-8b7c-48fe14215c20.png)

The tester should see the screen change to something like this:
![Screen Shot 2020-01-08 at 4 10 53 PM](https://user-images.githubusercontent.com/20731897/72016315-8c7cd900-3231-11ea-9259-ddb0ffc805f4.png)

4. Test should click the 'select element' tool shown here:
![Screen Shot 2020-01-08 at 4 10 53 PM](https://user-images.githubusercontent.com/20731897/72016431-c6e67600-3231-11ea-858c-f4afd7f0e2ad.png)

5. Once that 'tool' is selected, the user should scroll over every single icon is being populated via assets.boston.gov/...
![Screen Shot 2020-01-08 at 4 13 56 PM](https://user-images.githubusercontent.com/20731897/72016565-03b26d00-3232-11ea-98af-f017a2acc751.png)

6. Tester should report if any icon _is not_  being populated from assets.boston.gov/...

**Comment by gretchen-grozier** [comment]
@DineshBaddam can you run through steps @reillyzlab outlines above pls?

**Comment by DineshBaddam** [comment]
I have validated all the application icons location and they all are populating from assets.boston.gov/icons/accessboston/

These are the applications that I have validated
![image](https://user-images.githubusercontent.com/39305170/72087861-2a76af00-32d7-11ea-9688-fcd309b30a8c.png)

Thank,
Dinesh.

**Comment by phillipbentonkelly** [comment]
Ok, I pushed this to prod and double checked the urls.
