### ISSUE TITLE
Access Boston: update to an error message

### ISSUE THREAD

**Issue by gretchen-grozier** [CityOfBoston/digital#521]
BPS asked us to update the error that users see when they click 'Forgot Password?' off login page -- since it's specific to Registration (and most users are registered now).  More often, people don't have an active account.  Proposed wording change is in this Google Doc

https://docs.google.com/document/d/13A6AVXYV3SuWt4rKwq8Ilo-XzLTWu5wBNiKUVVvdr5A/edit?usp=sharing

Not a high priority - it's nice to have but not mission critical by any means

**Comment by phillipbentonkelly** [comment]
Meet with @samkatta and @NavanK, they said this page is on Ping and Navan would take care of it.
