### ISSUE TITLE
Access Boston: Group management - make sure no inactive users display

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#527]
For group management > people: Make sure no inactive users display in the data/user interface.

**Comment by phillipbentonkelly** [comment]
Person search should not be returning inactive users; will filter out inactive users from the Group Edit view.

**Comment by phillipbentonkelly** [comment]
This is done, the only place you will see an inactive user is when you view a Group's members. Person search filters out inactive by default.
