### ISSUE TITLE
Access Boston: Group management - Implementing filtering and showing of groups

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#528]
For group management: 

- [ ] Implement filtering and showing of groups
- [ ] Ensure this is working properly

Make sure we're considering pagination in this implementation, because some of these will turn back a large number of groups. Pagination can be number at bottom of screen pagination (which we have a design and maybe a patterns component for) or progressive scroll/disclosure, whichever is easier to implement.

**Comment by phillipbentonkelly** [comment]
Going try implement the easiest solution for this, then ask Sebastian for UI input.

**Comment by reillyzlab** [comment]
Pagination is implemented, but the styling isn't 100% accurate.

See boston.gov/news for accurate styling.

**Comment by reillyzlab** [comment]
Hover state missing on 'previous' and 'next'

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier, deploy to PROD for this issue has started, I made some last minute changes so the build/completion time is behind. ETA 5:30 - 6pm

**Comment by phillipbentonkelly** [comment]
Deploy finished, live on PROD
