### ISSUE TITLE
Access Boston: Group management - Implement New UI for Searching Groups Based on Number to Display

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#529]
In group management, some users have only a group of groups to manage/get displayed, so the search feature for that is too heavy. However, some people have a ton of groups so the search should be used. 

There needs to be a conditional call depending on the number of groups as to what UI should displayed/be interacted with. A large number of groups displaying should use the search bar. A small number of groups should use a new interface.

@sebastianebarb to help @phillipbentonkelly with a small number of group UI

@gretchen-grozier to provide the number of groups considered 'small number' (some people thought 2-3, others thought 10)

**Comment by reillyzlab** [comment]
Related to #528

**Comment by gretchen-grozier** [comment]
It would be 2-3 (so those folks get the glory).  Then we have the higher end (Lagan which has 200+)

**Comment by gretchen-grozier** [comment]
@reillyzlab sorry forgot to tag that last answer

**Comment by albertboston** [comment]
What's the ask on my part?

**Comment by reillyzlab** [comment]
Appears as if we didn't fully implement this. Need to decide what's going to be done or what needs to be done.

**Comment by reillyzlab** [comment]
API portion of this was completed last week. Phil working on the UI today.

**Comment by phillipbentonkelly** [comment]
Update: @gretchen-grozier, this is up on TEST and DEV for review. Displaying for users with less than 4 groups to manage

**Comment by gretchen-grozier** [comment]
@DineshBaddam Can you test this please?

**Comment by DineshBaddam** [comment]
I have Validated this in Test Environment with a couple of Users  and Seeing Two Different UI's
Displaying Users 2 Group Management Groups 
![image](https://user-images.githubusercontent.com/39305170/70357830-e0b52780-1845-11ea-8846-3012927aca46.png)
Another User with more number of Group Management groups 
![image](https://user-images.githubusercontent.com/39305170/70357958-3689cf80-1846-11ea-8445-d2c123ed0597.png)

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier, The deploy finished, I thought I had a PROD account that I could use to verify but I can't find it. Maybe it was my main account that was temp provisioned, am not sure. I can roll back the change in the morning if anything didn't work.

**Comment by gretchen-grozier** [comment]
Moved to Prod, will alert users - they will let us know if it is not working for sure.  Thanks @phillipbentonkelly

**Comment by gretchen-grozier** [comment]
@phillipbentonkelly bug that when people actually take action (add/remove) they don't see it in the UI. Caching issue?  Need immediate fix...pls advise when you will be ready for us to test!

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier the fix is on DEV/TEST and ready to confirm.

**Comment by gretchen-grozier** [comment]
@DineshBaddam can you please test.  The issue is that you make a change (add/remove) and that isn't reflected in the UI

**Comment by DineshBaddam** [comment]
@gretchen-grozier I have validated this in Test Environment by adding and removing users in the group and UI is updating immediately.

**Comment by reillyzlab** [comment]
Was deployed on 12/11.
