### ISSUE TITLE
Access Boston: Create documentation for VPN access to LDAP

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#531]
Access Boston: Create documentation for VPN access to LDAP for Security to have/know.

**Comment by phillipbentonkelly** [comment]
Still working on this

**Comment by reillyzlab** [comment]
Phil actively working on this documentation.

**Comment by phillipbentonkelly** [comment]
Finished documentation and pushed to PROD, can be found here: https://github.com/CityOfBoston/digital/tree/develop/services-js/group-mgmt
