### ISSUE TITLE
Access Boston: wording update to password pages

### ISSUE THREAD

**Issue by gretchen-grozier** [CityOfBoston/digital#534]
for the 3 password pages:  Registration (set original password), Change Password and Forgot Password  we need a new to add some words for new configurations (ADs upgraded to 2012 with harder password rules).

![image](https://user-images.githubusercontent.com/44211968/67515662-1bd01280-f66d-11e9-9877-fc55161ab852.png)

Change first sentence to:  Don't use personal info, like your name, ID or address.  
Add sentence: If you use just two consecutive characters from your name or ID in your password, it will fail
Then last sentence stays the same.

**Comment by gretchen-grozier** [comment]
@reillyzlab Is this the process I should follow to submit issues with ABP to Digital?  Just wondering when this change might get scheduled?

**Comment by reillyzlab** [comment]
@gretchen-grozier is this urgent or can we do during bash week (week of 11/18)?

**Comment by gretchen-grozier** [comment]
It's urgent, we have 12K users who aren't being given the correct info (not that they will read it, but it's a lot to ask the BPS Help Desk to carry this water).  I'd prefer not to wait @reillyzlab   It seems pretty easy....it's just a screen change.

**Comment by reillyzlab** [comment]
@gretchen-grozier this is on Access Boston dev - change password for you and team to review.

**Comment by gretchen-grozier** [comment]
Checking with Greg and James... I feel like it's confusing but I've got no better ideas!

**Comment by gretchen-grozier** [comment]
from James: I would just throw an "also" in that last sentence: "Your new password will also have to be..."
Last sentence should now be (if it's easy to do): Your new password will also have to be different than your last 5 passwords.
So good to go to TEST

**Comment by reillyzlab** [comment]
Went out to production/completed
