### ISSUE TITLE
Access Boston: Back button different than registry suite

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#546]
Access Boston Group Management has this back button: 

![Screen Shot 2019-11-18 at 1 37 51 PM](https://user-images.githubusercontent.com/20731897/69079743-a86db680-0a08-11ea-81e7-6defb5021f00.png)

Registry suite has this: 
![Screen Shot 2019-11-18 at 1 38 18 PM](https://user-images.githubusercontent.com/20731897/69079773-b7ecff80-0a08-11ea-92bb-8a2be26ded29.png)

These should match.

**Comment by reillyzlab** [comment]
In talking with @sebastianebarb we should: 
- [ ] Keep the blue square on Access Boston, but this should only say 'Back' not 'go back'

**Comment by reillyzlab** [comment]
@gretchen-grozier small change

I verified this is working as expected

**Comment by gretchen-grozier** [comment]
@reillyzlab @phillipbentonkelly   Looks good for me too.  Let's include this in the CR for tonight too!

![image](https://user-images.githubusercontent.com/44211968/69572471-33fbc000-0f92-11ea-8d06-553d14c13428.png)

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier, deploy to PROD for this issue has started, I made some last minute changes so the build/completion time is behind. ETA 5:30 - 6pm

**Comment by phillipbentonkelly** [comment]
Deploy finished, live on PROD
