### ISSUE TITLE
Access Boston: Change sort order by Last name, First name

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#547]
Change sort order by Last name, First name rather than employee ID (which is what is happening now.

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier, 

I added a sort flag to the server (DEV) request from the digital app and the results don't change. The docs that I found say that if the results don't change then sorting is either disabled or not installed. It looks like the sorting needs to be enabled/install on the LDAP server. The results makes me think they are not. The next step, to unblock this, would be to have someone look at the LDAP server and how/if sorting is enabled and set a default field (displayname) to use. After that we can test how the results are coming back to the client side, aka, if we past a sort flag is it taking effect.

- https://stackoverflow.com/questions/11641229/ldap-server-side-sorting-really-a-good-idea
- https://stackoverflow.com/questions/31067210/how-does-ldapsearch-sortorder-work
- [LDAP Control Extension for Server Side Sorting of Search Results](https://tools.ietf.org/html/rfc2891)

I did a test of what it would like if we sorted on the front end it did not go well, when I started to look at +500 results the spinner would go on for minutes.

**Comment by gretchen-grozier** [comment]
@NavanK Can you confirm that FID supports the function for sorting....see Phil's comment.   Having FID do the sort is preferable to trying to build on the Portal side.   We would want sort on 'Display Name' (both for groups and persons)

**Comment by NavanK** [comment]
FID does not support the Sorting, it is already sorting the users based on the employee ID. I think on the portal side it is needs to filter out to sort based on Display Name.

**Comment by gretchen-grozier** [comment]
this is still a requirement that we need built.  The UX for those with groups of several thousand users (and more apps to come with that volume) is impossible at the moment. @phillipbentonkelly had a way to do this (just more work).

**Comment by jfalvey** [comment]
Phil does not have a way to do this, it needs to come from the server pre-sorted, which is what the LDAP documentation online also says. It remains a question if it can sort based on multiple fields, it seems like it should. Closing for our work currently, but this can remain a requirement for a future project phase, which Greg and I are requesting as an FY21 Budget Request. Suggest working with FID to stop sorting on employee ID and instead sort based on Display Name.
