### ISSUE TITLE
Access Boston: Group management not opening in new tab (and should)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#549]
Group management not opening in new tab and should.

All other functionality of Access Boston opens in new tab, so this should match the rest.

**Comment by phillipbentonkelly** [comment]
Update: @gretchen-grozier, this is up on TEST and DEV for review

**Comment by gretchen-grozier** [comment]
Asked Dinesh to test!

**Comment by DineshBaddam** [comment]
@phillipbentonkelly Its is working as expected in Both Dev and Test when the user clicks on the Group Management link it is now opening in new tab.

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier / @DineshBaddam , This also deployed to PROD yesterday. Let me know if you see it.
