### ISSUE TITLE
Access Boston: If user doesn't have anything in 'support tools' then this header shouldn't appear

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#550]
If user doesn't have anything in 'support tools' then this header shouldn't appear, much like other functionality on Access Boston that shows/doesn't show based on roles.

![Screen Shot 2019-11-18 at 3 18 18 PM](https://user-images.githubusercontent.com/20731897/69089974-b1658480-0a16-11ea-9157-adb41dd95d30.png)

**Comment by reillyzlab** [comment]
@phillipbentonkelly confirmed fixed on test for me. 

@gretchen-grozier do you want to also verify this on test and let us know when we should move to production (as well as put in a change ticket)

**Comment by gretchen-grozier** [comment]
I confirmed with a couple test accounts (not mine, in Test I have ALL the Support Tools).  But my basic BPL and a random sponsored account I just set up for AgilePoint testing.  Looks good. @phillipbentonkelly Would say it's good for Prod @reillyzlab I have a CR in for tonight (we have a bug fix) should we tag this on???

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier, deploy to PROD for this issue has started, I made some last minute changes so the build/completion time is behind. ETA 5:30 - 6pm

**Comment by phillipbentonkelly** [comment]
Deploy finished, live on PROD

**Comment by gretchen-grozier** [comment]
Code pushed to Prod, confirmed 'Support Tools' is not displaying for end users any longer.
