### ISSUE TITLE
Registry: Update Back button to match styling on Group Mgmt

### ISSUE THREAD

**Issue by phillipbentonkelly** [CityOfBoston/digital#552]
Access Boston Group Management has this back button: 

![Screen Shot 2019-11-18 at 1 37 51 PM](https://user-images.githubusercontent.com/20731897/69079743-a86db680-0a08-11ea-81e7-6defb5021f00.png)

Registry suite has this: 
![Screen Shot 2019-11-18 at 1 38 18 PM](https://user-images.githubusercontent.com/20731897/69079773-b7ecff80-0a08-11ea-92bb-8a2be26ded29.png)

These should match. Update Registry back button to match Group Mgmt

- [ ] Adjust the back button to the square with the words 'Back' on registry: birth, marriage, and death

**Comment by stephaniemar** [comment]
Hey @carolinestj is this something that needs to be done

**Comment by carolinestj** [comment]
@stephaniemar I think it would be a good question to ask the group, I personally like the blue square button better then just the text option
