### ISSUE TITLE
Add Boston.Gov (Content Editor) icon to the Access Boston Portal

### ISSUE THREAD

**Issue by gretchen-grozier** [CityOfBoston/digital#555]
Have requested icon from Sebastian and updated the Portal Content sheet with details (URL, group)

https://docs.google.com/spreadsheets/d/1OiH2HBLE55X8MzGaB7H9VC_a2WpQQcjV4-eyNpJGTPY/edit#gid=0

**Comment by gretchen-grozier** [comment]
icon has been received, groups are in the various environments in FID and populated with user list from James - so we can move forward with coding onto the Portal now @reillyzlab assigning to you to give to the right Digital resource.  Thx

**Comment by gretchen-grozier** [comment]
@sebastianebarb can you make sure @phillipbentonkelly has the icon needed for this (boston.gov content editors)?
@duffy-james besides James who would you like to be able to manage the user group (to add someone who can access the icon)?

**Comment by andrebtlima** [comment]
@gretchen-grozier, jumping in here because I'm going to be taking on the product management side of Boston.gov, I should also be able to manage that user group. Thanks!
