### ISSUE TITLE
Order ID collision: https://rollbar.com/CityofBoston/registry-certs/items/176/

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#564]
Order ID collision: https://rollbar.com/CityofBoston/registry-certs/items/176/

*Added by Fiona*

**Comment by stephaniemar** [comment]
check with @davidrkupton on this one

**Comment by davidrkupton** [comment]
I propose we close this one.  The link is dead (probably the event has been archived).
We can monitor rollbar errors and while there is one related to stripe that occurs after deploy which is somewhat concerning, there have never been any complaints from patty or users, so I suspect its more of a notice than an alert.
For good housekeeping, lets remove this and we can add back in a new, similar issue if necessaery.

**Comment by stephaniemar** [comment]
Yeah, Patty had no idea what this was.
