### ISSUE TITLE
new application for Access Boston Portal (Riskmaster)-August 5

### ISSUE THREAD

**Issue by gretchen-grozier** [CityOfBoston/digital#567]
Test integration in early January.   Icon is in Google Drive.  They prefer the briefcase one https://drive.google.com/drive/u/0/folders/1g4fnsRgoHokQwopGDbp0cGe1-NANHkQP

Please place the icon at the end (near Tableau)

Test URL:  https://rmaprdcityofboston.dxc-ins.com/RiskmasterUX/#/login  

Prod URL: https://rmaprdcityofboston.dxc-ins.com/RiskmasterUX/#/login  

(please note - same URL for both environments, there is a toggle once you login)

Security Group to see the icon is SG_AB_RISKMASTER

Prod go-live date pending integration with PS HCM (Kerry Nero says on 2/18)

**Comment by phillipbentonkelly** [comment]
@gretchen-grozier, are we using the test url on both Test and Dev? Or do we need a Dev URL too?

**Comment by gretchen-grozier** [comment]
@phillipbentonkelly they only have 2 environments -  Test (which they call Training) and Prod. TY

**Comment by phillipbentonkelly** [comment]
This is on DEV and Test. I used Riskmaster as the label, let me know if it needs to be something else.

**Comment by gretchen-grozier** [comment]
@phillipbentonkelly they don't have a Dev environment so we can take it off Dev....it's never going to be used.  I'll check with the app owner, but I've only ever heard it called Riskmaster by them.  I assume that's what the label should be.

**Comment by phillipbentonkelly** [comment]
Hi @gretchen-grozier, I stopped by to check on this task. Was you team able to QA it, etc. I don't know if you're still waiting on external stuff, but if not when do you think we should deploy this.

**Comment by gretchen-grozier** [comment]
@phillipbentonkelly First sentence of issue is "prod go-live is scheduled for 3/2".  ; )  The business owners are still working on testing as far as I know.

**Comment by reillyzlab** [comment]
This will not go live for a while, because it has been decided that this will not go live until an integration between Riskmaster and HCM happens. This integration is still being planned.

**Comment by andreeaursu1981** [comment]
LIVE DATE=June 30

**Comment by andreeaursu1981** [comment]
New Live date --sometimes in JULY

**Comment by andreeaursu1981** [comment]
LIVE Date= July 29

**Comment by andreeaursu1981** [comment]
New LIVE Date from Stakeholders = Aug 5

**Comment by andreeaursu1981** [comment]
PROD URL: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Frmaprdcityofboston.dxc-ins.com
Group For RiskMaster: cn=SG_AB_RISKMASTER
Icon: https://drive.google.com/drive/u/0/folders/1j4RV6uBZ3mkHGotxEoGcRTGxt5byqpjQ

**Comment by phillipbentonkelly** [comment]
Icon on assets.boston.gov: https://assets.boston.gov/icons/accessboston/Riskmaster2.svg

**Comment by phillipbentonkelly** [comment]
@andreeaursu1981, @NavanK, the deploy just made it to the AWS's 'Codebuild'. From there it usually takes 10-20min to be live.

**Comment by phillipbentonkelly** [comment]
@andreeaursu1981, @NavanK, the build finished and the app should be on PROD

**Comment by andreeaursu1981** [comment]
This can be closed. I do not have the permission to close this one. Thanks friends.
