### ISSUE TITLE
Add Tableau to the Access Boston Portal-2/14/20

### ISSUE THREAD

**Issue by gretchen-grozier** [CityOfBoston/digital#575]
Prod go-live is scheduled for Saturday, February 15 (so we can do this work late afternoon on Friday the 14th).

Prod URL: https://dashboard.cityofboston.gov/

Icon is 
![Data icon 3](https://user-images.githubusercontent.com/44211968/72292310-202e1b00-361f-11ea-8707-a20d33b82998.png)  [Sebastian can probably point out where it is in the Access directory]

Icon at the end (so last app shown for anyone who has it) please

This is only shown to members of the security group: SG_AB_TABLEAU

Only doing this integration in PROD, not in DEV

**Comment by gretchen-grozier** [comment]
@mmcgowanBOS I have actually talked to Phil about this, also I don't have confidence it's going to happen this weekend - still troubleshooting with Data Analytics on SAML integration (not fully working in Dev)

**Comment by gretchen-grozier** [comment]
@phillipbentonkelly @mmcgowanBOS **Postponed - will let you know new date**

**Comment by gretchen-grozier** [comment]
@andrebtlima and @phillipbentonkelly confirming go-live with Tableau is on for this weekeend (2/15) so Digital can do the work for ABP late afternoon on Friday the 14th.  Can you confirm you have what you need to complete this task?

**Comment by reillyzlab** [comment]
This will be done afternoon of Friday, 2/14 by @phillipbentonkelly by 3:30 p.m.

@phillipbentonkelly will actively communicate in this ticket when the work has been completed. @reillyzlab will ensure @gretchen-grozier is told in person that the work has been completed.

**Comment by gretchen-grozier** [comment]
@phillipbentonkelly and @reillyzlab can see icon on the ABP.  Login isn't done yet, but will have folks test tomorrow once Tableau team finishes their upgrade,  Thanks!!
