### ISSUE TITLE
Set up Google Analytics within City of Boston analytics property.

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/digital#581]
Create new property in Google Analytics for permit finder and cooridinate with Tag Manager ID.

**Comment by mmcgowanBOS** [comment]
@phillipbentonkelly , I've gone ahead and set up a new container in Tag Manager for Permit Finder. Its ID is "GTM-5MT2HTJ". I haven't published it yet, but once you've had a chance to update the code base with the ID and other related bits, I can test to make sure it's working.
