### ISSUE TITLE
Access Boston Icon: GovQA- Aug 24

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#582]
Name of the application = GovQA
Description of what the app is = data tool/used by PIOs/Comm Officers in depts (more details from Kimberly Lucas?)
Timeline = mid February [per comments from Gretchen on 1/3]; Reilly knows from Sarah/Shawn that this will be closer to mid- to late-March. No exact launch TBD

![GovQA icon](https://user-images.githubusercontent.com/20731897/74480202-7b516880-4e7e-11ea-8425-f73d7c2d5d53.png)

**Comment by andreeaursu1981** [comment]
Was added to test environment on 6/1/20

LIVE DATE = August 28, 2020

**Comment by andreeaursu1981** [comment]
Can we assign this git to Phil as we have issues with tile in TEST? Thanks

**Comment by reillyzlab** [comment]
Pulled from email:

Hi Phil, @phillipbentonkelly 

I remember we put the GovQA tile in TEST Access Boston, however we can't see it. Dinesh is part of the group, yet he can't see the tile. Can you look into this or do you think a quick meeting will solve this faster? Let us know. 
This is not an emergency and we can wait another week.

Thanks.
Andreea

**Comment by andreeaursu1981** [comment]
Prod GovQA UR : 
https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=bostonma.govqa.us  

Security Group: cn=SG_AB_GOVQA

**Comment by mmcgowanBOS** [comment]
I spoke to Phil and he believes that this is currently live in Prod. I'm going to assign to Andrea. If she can confirm that this is complete, please close. If not, please make a comment an re-assign back to Phil and/or myself.

Thank you.
