### ISSUE TITLE
Access Boston Icon: OpenGov-no launch date

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#583]
Name of the application = OpenGov (formerly Analyze Boston)
Description of what the app is = City of Boston's open data hub. We invite you to explore our datasets [this will be on the ABP for every users]
Timeline = end of February (as of 1/3); no launch date set

![OpenGov Icon](https://user-images.githubusercontent.com/20731897/74480494-05013600-4e7f-11ea-8d45-1d0b08383961.png)

**Comment by mmcgowanBOS** [comment]
I spoke to Phil and we're not exactly sure what the status of this may be. Is this the same as "GovQA"? I'm going to assign to Andrea. If she can confirm that this is all set (or a duplicate), please close. If not, please make a comment an re-assign back to Phil and/or myself.

Thank you.
