### ISSUE TITLE
Registry: Uploading images/documents too large error + need to re-upload

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#584]
On the Registry suite (birth, marriage, and death certificate applications), when a person has to upload proof of identity and the file is too large they get an error message (see below).

However, there is no way for a user to know/be prompted to re-upload an image if they get the 'image is too large' message.

![Screen Shot 2020-02-13 at 1 40 44 PM](https://user-images.githubusercontent.com/20731897/75052136-165cca80-549d-11ea-940d-075c9fb92ce0.png)

We need to build in a way for people to re-upload the image.

**Comment by reillyzlab** [comment]
To resolve:

For both images, if people get the 'upload: failed; image too large' message. Add to that message: Click here to re-try upload.

**Comment by stephaniemar** [comment]
This is a duplicate #585
