### ISSUE TITLE
Registry: Uploading images file constraints messaging and display

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#585]
On the Registry suite (birth, marriage, and death certificate applications), when a person has to upload proof of identity and the file is too large they get an error message (see below).

There is messaging to say that a file was too large, but a user has no way of knowing what file constraints exist (i.e. size, type). We need to provide messaging/UI for people to know this.

![Screen Shot 2020-02-13 at 1 40 44 PM](https://user-images.githubusercontent.com/20731897/75052578-d6e2ae00-549d-11ea-8723-f4db36fcf123.png)

**Comment by reillyzlab** [comment]
![Screen Shot 2020-02-13 at 1 40 31 PM](https://user-images.githubusercontent.com/20731897/95487043-6d92ab00-0959-11eb-8c7e-c4a8b682664e.png)

**Comment by reillyzlab** [comment]
![Screen Shot 2020-02-13 at 1 40 31 PM](https://user-images.githubusercontent.com/20731897/95487130-87cc8900-0959-11eb-8353-30d59e388536.png)

**Comment by reillyzlab** [comment]
How to resolve this issue:

- [ ] Photo upload only allows for JPG in code, only jpg should be allowed. This ensure that a preview of the image can be seen. (Right now a PDF can be submitted, but shows up as a blank image in the preview screen.) 

- [ ] Maximum upload is also 15 MB, anything above 12 is failing. This needs to be resolved.

- [ ] Add the file type and size language under the upload ID images. Add below the bulleted list and above the boxes for the images. Should be its own line. Match body text. Language to use:
Files should be JPG format, and under 15MB.

**Comment by stephaniemar** [comment]
Draft some language for review with Patty's team around this
