### ISSUE TITLE
Registry: Translation for the entire registry suite

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#590]
Implement translation for the entire registry suite like we've done for other web apps.

Presumably, we can make the changes for one and match it quickly to the others.

All registry certificates and intention.

First Translations:
- Spanish 
- Chinese

**Comment by reillyzlab** [comment]
@mmcgowanBOS Can I give this to you to run with/look into how we can implement?

**Comment by mmcgowanBOS** [comment]
OK. I too just added Phil so both have this on our radar. Will bring this up at the next meeting.

**Comment by stephaniemar** [comment]
We should ask Sarah for appropriate funding Channel for this.
