### ISSUE TITLE
Registry: Adjustments needed to apostille language

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#593]
The Apostille information (under the carat/unexposed content) here is outdated: 

https://registry.boston.gov/marriage/review

https://registry.boston.gov/birth/review

--
According to Patty, A Hand Signature on a birth certificate is no longer needed.
The Massachusetts Secretary of State's Office does not require a Hand Signature - they accept the Boston Registrar's signature (my signature) when it is electronically signed or my stamped signature.

They do require a RAISED SEAL and we provide that on all certificates. They will not accept a photo copy because it does not have a RAISE SEAL. 

So once you receive your Certified copy from us you then submit your certificate to the Massachusetts Secretary of State for an Apostille https://www.sec.state.ma.us/pre/precom/comidx.htm (ignore styling on this section)
--

**Changes to make:** (on both birth and marriage certificates, note: language varies slightly on each site)
- Keep title of page and all other content below the body copy on the page the same, but change the body copy.
- All body copy can be exposed, so remove the carat/the content being buried in a drawer.
- Have the body copy read (just replace all of the content) as the following: https://docs.google.com/document/d/1CMQQAY7tkCQeU-z0Kdh-xphAttbYZYWeIZANB26k_lM/edit

--
The changes should be done and then put onto staging, QAed by digital, run by/approved by Patty [Reilly will do this], and then go to production.

**Comment by phillipbentonkelly** [comment]
@reillyzlab, I staged the changes.

- https://registry-certs.digital-staging.boston.gov/birth/review
- https://registry-certs.digital-staging.boston.gov/marriage/review

**Comment by reillyzlab** [comment]
These look good. I'll send them to Patty to give them a once over, before we move them to production.

**Comment by reillyzlab** [comment]
@phillipbentonkelly Patty this is good, so let's push live whenever you're able.

**Comment by reillyzlab** [comment]
Pushed in June, but ticket was never closed. Closing ticket because work is complete.
