### ISSUE TITLE
Access Boston: Authentication Configuration Allows MFA Bypass-"space" added after the username

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#600]
needs data validation behind the scene to trim any spaces or unwanted character

**Comment by phillipbentonkelly** [comment]
This will take about 1-2hrs, mostly for back and forward between Navan and I after I give him the snippet of code to put in the template and testing.

**Comment by reillyzlab** [comment]
Goal: Have this in test instance of Access Boston by end of week of 7/20/20.

**Comment by reillyzlab** [comment]
This is on Access Boston test environment as of today.

**Comment by andreeaursu1981** [comment]
@phillipbentonkelly @reillyzlab Phil will still have to put it in PROD.

**Comment by phillipbentonkelly** [comment]
@andreeaursu1981, @reillyzlab I just remember that this change was made on the files the security team hosts so I would not be involved in the deployment to PROD.

Phill

**Comment by NavanK** [comment]
That is correct @phillipbentonkelly . I will be pushing that change to Prod environment, since I have the templates. Thanks.

**Comment by NavanK** [comment]
Changes moved to Production.
