### ISSUE TITLE
Access Boston- PingID Device management enhancements

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#601]
Jira: https://bostondoit.atlassian.net/browse/DIG-53

Request to build 6 new templates: Manage My Devices, Add devices, Change authenticated device, etc. 
Documentation is here: https://apidocs.pingidentity.com/pingid-api/guide/pingid-api/pid_c_PingIDapiUserManagement/#:~:text=The%20PingID%20user%20management%20API,user%20in%20the%20PingID%20service

**Comment by phillipbentonkelly** [comment]
I think this is the one Jeanethe will provide a timeline of when we can tackle.

**Comment by reillyzlab** [comment]
This is on me to figure out when they can be fit into our roadmap. I am doing this this week (pending nothing else interrupts). May need to partner with Andreea or someone to get additional info.

**Comment by andreeaursu1981** [comment]
THIS IS ON HOLD

**Comment by g-grozier** [comment]
@stephaniemar this is still something we want to do.  I'm exploring hiring a web developer for our team given the constraints with Digital doing development work.  But if you could let me know when you might be able to do it...

**Comment by stephaniemar** [comment]
@g-grozier @davidrkupton @phillipbentonkelly this one looks old but it seems Gretchen commented in Jan they still want this done. I am not sure I understand the ask here.

**Comment by ggrozierBOS** [comment]
We want to "Boston-ize" the screens under the Manage My Device(s) link.  Which are horrible Ping UI...

![Screenshot 2022-06-07 112926](https://user-images.githubusercontent.com/104460350/172420824-222aa512-ed1d-4c9b-ae2d-31d2ccaf2eff.jpg)
