### ISSUE TITLE
Access Boston: Add SG_AB_BLDGMAINTREQ under Building Maintenance Form

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#603]
- title: Building Maintenance
        url: https://assetessentials.dudesolutions.com/CityOfBoston/MyRequest/Add
        agencies:
          - CH
ADD: 
SG_AB_BLDGMAINTREQ

Please leave the CH as well. 

Thanks!

**Comment by andreeaursu1981** [comment]
Can you please open this up because it is not fixed. Thanks

**Comment by reillyzlab** [comment]
Estimation 2-3 hours to implement this.

**Comment by reillyzlab** [comment]
'OR' also needs to added to the platform overall as an applicable function

**Comment by reillyzlab** [comment]
Goal: Have this in test instance of Access Boston by end of week of 7/20/20.

**Comment by phillipbentonkelly** [comment]
@NavanK, I pushed a fix to the TEST environment. Check it out when you can and let me know if it works. We can discuss it after 10:30 AM.

TEST Env Config: https://github.com/CityOfBoston/access-boston-config/blob/master/src/configs/test/apps.yaml

**Comment by NavanK** [comment]
Thanks @phillipbentonkelly I will validate this and let you know.

**Comment by NavanK** [comment]
@phillipbentonkelly I have completed the validations and it is working now. I will ask @DineshBaddam to validate also and will take it from there. Thanks.

**Comment by DineshBaddam** [comment]
Hi, 
I have Validated this with CH user and user have the Building Maintenance link, and also tested another department user who is in Security group SG_AB_BLDGMAINTREQ also able to see Building Maintainance link.
Thanks,
Dinesh.
