### ISSUE TITLE
Xybion LIVE Date - 10 Aug 

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#607]

**Comment by andreeaursu1981** [comment]
For Philip

**Comment by andreeaursu1981** [comment]
Changing LIVE date for Friday because Stakeholders need this live for Aug 10 9 am.
URL: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fma.xybion.com%2Fsso%2Fmetadata.xml
Group: SG_AB_XYBION
Tile: https://drive.google.com/drive/u/0/folders/1j4RV6uBZ3mkHGotxEoGcRTGxt5byqpjQ

**Comment by mmcgowanBOS** [comment]
Just an FYIL. Ill be OOO starting 8/10 - 8-15.

**Comment by phillipbentonkelly** [comment]
@andreeaursu1981, is this an app that goes at the top of the dashboard or does it belong to one of the sections? We have an icon for this on our assets servers so am not sure if it belong with the other apps with icons.

Icon on Assets: https://assets.boston.gov/icons/accessboston/Xybion.svg
