### ISSUE TITLE
Access Boston Icon - Hootsuite 

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#612]
Name of the application: Hootsuite

Description of what the app is (if it is not that obvious): social media app

Timeline (when do you need to have live in Prod): 2 weeks

**Comment by andreeaursu1981** [comment]
Please assign this to Sebastian. I do not have access. Thanks!

**Comment by sebastianebarb** [comment]
Hey, @andreeaursu1981 I juts sent you the icon for review via email. in the future do you min putting tickets for creative in our repository? https://github.com/CityOfBoston/creative-team-workflow

**Comment by g-grozier** [comment]
this app is unknown to me (in terms of a request to integrate it with Access Boston).  If the app owner is still interested we can re-open.
