### ISSUE TITLE
Access Boston TEST PSFN TILE URL

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#613]
Under PSFN tile the URL should be this: 

   https://baisfntst.cityhall.boston.cob/psp/idmtstfn/EMPLOYEE/ERP/h/?tab=DEFAULT

**Comment by phillipbentonkelly** [comment]
@andreeaursu1981 the update finished deploying

**Comment by andreeaursu1981** [comment]
Thanks Phil!
