### ISSUE TITLE
Registry: Footer should be left aligned - all apps

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#618]
On all the registry applications, all of the footer content should be left aligned.

It's what reads, 'questions...'

**Comment by reillyzlab** [comment]
This applies to all certificates and the intention.

If possible to do this for all the same time, great. If not, focus on intention.

**Comment by phillipbentonkelly** [comment]
Is this still an issue? Spot checking the footer on the web app and boston.gov they look the same, have the same alignment.

**Comment by reillyzlab** [comment]
This is referring to this:

![Screen Shot 2020-12-29 at 4 53 01 PM](https://user-images.githubusercontent.com/20731897/103316388-f7e52b00-49ed-11eb-983a-7daabb2044a9.png)

**Comment by phillipbentonkelly** [comment]
Ok, this makes sense now. thx

**Comment by phillipbentonkelly** [comment]
On Staging
https://registry-certs.digital-staging.boston.gov/marriageintention
https://registry-certs.digital-staging.boston.gov/birth
https://registry-certs.digital-staging.boston.gov/marriage

**Comment by jimmurphy-boston** [comment]
Looks good.

**Comment by phillipbentonkelly** [comment]
Deployed
