### ISSUE TITLE
Registry: Width of fields adjustments

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#621]
![Screen Shot 2020-09-21 at 2 11 56 PM](https://user-images.githubusercontent.com/20731897/93804527-0ca26d80-fc0c-11ea-9c7a-b6fbd5b90b53.png)

Sebastian gave feedback at these 'should stretch to the right'. They've been adjusted to this:

![Screen Shot 2020-09-21 at 2 12 43 PM](https://user-images.githubusercontent.com/20731897/93804601-2c399600-fc0c-11ea-85ac-308f4a7b0af1.png)

They should go back to the original format and not each be full length width but rather that each line matches up on the right aligned side. (i.e. the three top name boxes evenly splitting and stretching to match the width of the last name/surname box and that city/town and state/province evenly 50/50 split but match the width of the hospital name.

**Comment by reillyzlab** [comment]
Step 4 (contact info and appointment date) still inconsistent for field box width - make consistent

**Comment by phillipbentonkelly** [comment]
We did this a while back, most fields are on their own row now. Closing
