### ISSUE TITLE
Registry: add google analytics

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#630]
Add generic google analytics to the site

**Comment by mmcgowanBOS** [comment]
Hi Phil,
I just checked the source code for all registry apps (death, birth, marriage) and I can confirm that they all use the same Google Analytics tracking id ("UA-99773468-7"). So you should be able to use the same approach / method that is currently in place. 

Let me know if you have any questions.

Thanks.

**Comment by reillyzlab** [comment]
We looked at google analytics together during stand up on 9/25 and it appears to be working so closing.
