### ISSUE TITLE
Registry: adjust email confirmation sender and content

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#631]
![image](https://user-images.githubusercontent.com/20731897/93911708-5b154200-fcc8-11ea-956c-31219acbd23e.png)

1. Can we match the sender of the other registry receipts instead of "boston.gov contact form"?

2. Can we adjust this current body language:

Marriage Intention Application
Thank you for your submission. Have questions? Contact us at
617-635-4175 or registry@boston.gov.

To instead say:
Thank you for submitting your marriage intention application. 

Have questions? Contact us at 617-635-4175 or marriage@boston.gov

3. Can we remove this footer content?
--------------------------------
This message was sent using the contact form on Boston.gov. It was sent by r d from marriage@boston.gov. It was sent from .

**Comment by mmcgowanBOS** [comment]
@phillipbentonkelly, here is the new endpoint I set up in the CI environment.
https://d8-ci.boston.gov/contactform/emails

You shouldn't have to change anything on the front end sending method, other than the endpoint domain itself. Let me know if you have any issues testing it. This is still a work in progress, but should match what's currently up on the AWS endpoint (minus the extra templated content Reilly mentioned).

Thanks.

**Comment by mmcgowanBOS** [comment]
@phillipbentonkelly , and @reillyzlab , I demo-ed the HTML capabilities during Demo Time up on the CI Acquia environment. It looks like we can address this before launch without too effort as it stands.

Reilly, ...

1. Can you supply what the "sender" name should be to match the other registry apps? 

2. For the email content piece, I remember you saying that you'd like to at the very least to just remove the content between the hash marks and the hash marks themselves. Did you want to try and apply and CSS / HTML style to the body of the email? I know we only have a week lelft to get this going and testing, so wouldn't suggest we try and rush a whole new email template design, but could add a few stylish things I suppose to improve the look and feel. I'm thinking bakcground color, border, and maybe a logo image? Thoughts?

**Comment by reillyzlab** [comment]
Sender/From: 
City of Boston Registry <marriage@boston.gov>

Regarding number two, correct it would be great to focus on getting this launched so it doesn't need too much effort put in and the text is fine but if it's possible/not too much work we could try to match the other registry certificates maybe at least for header and footer and text styling.

![Screen Shot 2020-09-28 at 10 43 40 AM](https://user-images.githubusercontent.com/20731897/94447262-35c48000-016f-11eb-9597-a94f42b8c14d.png)

**Comment by reillyzlab** [comment]
Simply do plain text as mentioned in the first portion of the ticket.

**Comment by mmcgowanBOS** [comment]
@phillipbentonkelly , I pushed the endpoint live to Prod yesterday and this morning updated the ENV vars so this should now properly work. 

**NOTE:** You will need to swap the "template_id" POST body param out with the Prod version. Please use "20558627".

Let me know if you have any issues or questions,

**Comment by reillyzlab** [comment]
Completed so closing
