### ISSUE TITLE
Registry: On contact info/phone number move location of description text

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#633]
On contact info/phone number move location of description text please put this description text under the title “(digits only, no spaces or dashes)”.

Please also rephrase to be “Numbers only, no spaces or dashes needed.”

**Comment by phillipbentonkelly** [comment]
@reillyzlab, applying this fix results in this look on Desktop. Let me know what you think.

![Contact-Phone-Desc-misaligned](https://user-images.githubusercontent.com/2627273/94036082-e9092f80-fd91-11ea-9f2c-a43631848dfe.JPG)

**Comment by reillyzlab** [comment]
@phillipbentonkelly in this two column format the field boxes should align at the top.

I'd recommend just adding a break line under email address (to match the extra description under phone) unless there's an easier way.

**Comment by reillyzlab** [comment]
Completed so closing
