### ISSUE TITLE
Registry: Digital Code Review

### ISSUE THREAD

**Issue by phillipbentonkelly** [CityOfBoston/digital#637]
Code review code for this project: https://github.com/CityOfBoston/digital/pull/620

Stella, Matt, (opt) David

**Comment by reillyzlab** [comment]
Phil will

- [ ] Put this in writing for folks to review the write up
- [ ] Follow up with a meeting if need be. Phil will schedule this.

**Comment by reillyzlab** [comment]
This meeting is happening on 9/29.

**Comment by phillipbentonkelly** [comment]
@mmcgowanBOS, please approve

**Comment by mmcgowanBOS** [comment]
HI Phil,
What exactly am I approving? If the code base, then "yes" this is approved. This isn't an actual PR so the traditional "approve" action can't be done from what I understand.

**Comment by phillipbentonkelly** [comment]
@mmcgowanBOS, this PR https://github.com/CityOfBoston/digital/pull/620
