### ISSUE TITLE
Registry: Add description text to birthplace city/town

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#643]
Add description text to birthplace city/town for both person a and b, which should be:

Please list the city/town where the hospital was located, not where your family was living.

Please match the formatting of the other description text.

**Comment by phillipbentonkelly** [comment]
@reillyzlab, since we're getting rid of the hospital field does it make sense to still reference a hospital here still?

**Would this due**: _Please list the city/town you were born in, not where your family was living._ 

I'll use the text you provided for now.

**Comment by reillyzlab** [comment]
Please keep with the original text suggested.

**Comment by reillyzlab** [comment]
Completed so closing
