### ISSUE TITLE
Registry: Place of birth location adjustments

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#644]
After Patty reviewed she gave the following feedback regarding birthplace:

Fields needed for person a and b: City/Town, State/Province and Country if not born in the United States

We do not need the name of the hospital -- we will remove. Put in a separate ticket for that: https://github.com/CityOfBoston/digital/issues/642

**Comment by reillyzlab** [comment]
@phillipbentonkelly 

Can you please verify that the fields are displaying as expected/working okay?

**Comment by reillyzlab** [comment]
![Screen Shot 2020-09-28 at 4 41 58 PM](https://user-images.githubusercontent.com/20731897/94483861-278f5780-01a1-11eb-9bb0-4d8d4e1950f5.png)

Birthplace location should have these field headers in this order:

1. birthplace city/town [write in field]

2. birthplace state/province [write in field]

3. birthplace country, if not born in the United States - drop down selection is fine, but is it possible to not have the United States listed (or at least listed first) so people don't select (if selected it will make it too long to fit for printing and will create more work for Registry staff)

**Comment by phillipbentonkelly** [comment]
@reillyzlab, I move the state field to be in between city and country. However, it's only visible after a country is selected because it only applies to the USA
