### ISSUE TITLE
Registry: Add field to 'suffix'

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#656]
Add a 'does not apply' item for suffix.

Add this for both person a and b.

**Comment by reillyzlab** [comment]
![Screen Shot 2020-10-14 at 9 44 35 AM](https://user-images.githubusercontent.com/20731897/95997579-8982ca80-0df9-11eb-8b8e-7c2205a3174e.png)

This is showing up as a pre-populated for everyone. 

This should be a field that someone selects from the dropdown like the rest of the numbers.

Make it required.

Match the case styling of the other 'does not apply' on the page which are: Does Not Apply

**Comment by reillyzlab** [comment]
This should not be showing as pre-populated for everyone. 

This field should start blank and people should have to select 'does not apply'. (Like the other drop downs on the app)

The field should be required so that if they don't have a suffix, then they will select 'does not apply'.

**Comment by phillipbentonkelly** [comment]
Deploying next to staging

**Comment by reillyzlab** [comment]
Still needs to be done:

- [x] Match the case styling of the other 'does not apply' on the page which are: Does Not Apply

- [x] This field should be required to answer.

**Comment by reillyzlab** [comment]
Completed so closing
