### ISSUE TITLE
Registry: Re-do location fields, remove state

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#658]
Re-do order of birthplace location fields

User should:
Select country first (i.e. put this as a the first field)

Reilly emailed Patty for additional information prior to finishing this ticket.

**Comment by jimmurphy-boston** [comment]
Beleive this was already address and put on staging for testing. tested and it does ask for country first then lets you choose city and state. If you chose another country it does not ask you for the State.

**Comment by jimmurphy-boston** [comment]
looks fine now
