### ISSUE TITLE
Registry: Review page - adjust marriage header to match other page styling

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#663]
On the review page: https://registry-certs.digital-staging.boston.gov/marriageintention?step=reviewForms

The sub-headers have underlines.

Add that to 'marriage' header for person a and b to match of the other sub-headers on the page.

![Screen Shot 2020-10-08 at 2 24 11 PM](https://user-images.githubusercontent.com/20731897/95498522-902cc000-0969-11eb-9a40-2f05b0c40eba.png)

**Comment by phillipbentonkelly** [comment]
If adding the 'underline' to the 'Marriage' header is the issue then its already been fix. Please let me know if there is more than that.

**Comment by jimmurphy-boston** [comment]
This has been resolved in Staging. can be closed when pushed to production
