### ISSUE TITLE
Registry: Review page - spacing issue for 'were your parents married at the time of your birth?'

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#676]
On the review page, for both partner a and b the following question 'were your parents married at the time of your birth?' has a spacing issue. 

There should be a space between the question/colon and the answer. There currently is not.

![Screen Shot 2020-10-23 at 4 34 42 PM](https://user-images.githubusercontent.com/20731897/97053329-59999c80-1548-11eb-9a6c-1f1f631808b0.png)

**Comment by phillipbentonkelly** [comment]
On Staging

**Comment by jimmurphy-boston** [comment]
Correct on Staging
