### ISSUE TITLE
Registry: Fields/headlines not matching for person and partner

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#687]
Throughout the application the people that are applying for the marriage intention are references as person a and person b. But, on the review page they are listed as partner a and partner b. 

Adjust the review page to be person a and b. 

Examples: 
![Screen Shot 2020-10-28 at 2 22 45 PM](https://user-images.githubusercontent.com/20731897/97490826-5da23180-192f-11eb-9957-e6431c087da9.png)

![Screen Shot 2020-10-28 at 2 20 39 PM](https://user-images.githubusercontent.com/20731897/97490860-6abf2080-192f-11eb-91e4-e73795f476b4.png)

**Comment by phillipbentonkelly** [comment]
Duplicate ticket, closing

**Comment by reillyzlab** [comment]
Duplicate of https://github.com/CityOfBoston/Iterators/issues/179
