### ISSUE TITLE
Registry: Place of Marriage

### ISSUE THREAD

**Issue by jimmurphy-boston** [CityOfBoston/digital#689]
Place of Marriage: The couple does not fill that in when they do their Intention - the Marriage staff adds that after the wedding when the marriage license is returned to us to Register as complete.

Patty thinks she isolated it: it is taking the Place of Marriage from the Party A the town they list for their residence:
![image](https://user-images.githubusercontent.com/63253451/97581091-875c6680-19ca-11eb-8fa2-07813d42a5ad.png)

**Comment by reillyzlab** [comment]
Jim will set up a meeting to over this with Rich

**Comment by reillyzlab** [comment]
Resolved so closing
