### ISSUE TITLE
Registry: Partnership Status

### ISSUE THREAD

**Issue by jimmurphy-boston** [CityOfBoston/digital#690]
Partnership 'Status': There seems to be a partnership status selected based on other fields with data. However, the actual status isn't coming through for Patty.

From Patty:
I am not sure where that information is coming from - it could be that when you are testing it you are entering data there - we do not get many responses from couples on that one so I am not sure.  It would seem that Partnership status would need to be filled in for there to then be data in Partnership State.   This info only is on the Int and never is seen on the marriage license itself.

Example from Patty: 

REILLY-TEST MIDDLE LAST | PERSON B-FIRST TEST MIDDLE-TEST LAST II | 10/28/2020
-- | -- | --

![image](https://user-images.githubusercontent.com/20731897/97584724-55e19c00-19c6-11eb-992a-017566fb07ba.png)

**Comment by phillipbentonkelly** [comment]
Rich is going to take a look at the Partnership Status issue, it may be a fix on his end or ours

**Comment by reillyzlab** [comment]
Still an issue. @phillipbentonkelly to loop back with @jimmurphy-boston on this

![image](https://user-images.githubusercontent.com/20731897/98161594-9ef18e80-1ea5-11eb-8b26-c01ebfbd227d.png)

**Comment by phillipbentonkelly** [comment]
This was fixed last week by Rich, we can double confirm in our meeting today but am moving this to the 'close' column
