### ISSUE TITLE
Registry: Mother and Father Information, Not all information coming through

### ISSUE THREAD

**Issue by jimmurphy-boston** [CityOfBoston/digital#691]
For mother and father, not all of the information is coming through.

This field appears to not be coming through for both parents for both person a and person b: PARENT 1/MOTHER - MAIDEN NAME/SURNAME AT BIRTH OR ADOPTION

It should be showing up like this for Patty:
They put:
Mary/Smith
John/Jones

Where if the parents had married and she took his last need then it would be:
Mary Jones/Smith
John Jones/Jones

or she did not take his name:
Mary Smith/Smith

or she was married or not married to John Jones but is married to someone else know:
Mary Jackson/Smith
John Jones/Jones

Example: 

REILLY-TEST MIDDLE LAST | PERSON B-FIRST TEST MIDDLE-TEST LAST II | 10/28/2020
-- | -- | --
![image (1)](https://user-images.githubusercontent.com/20731897/97596087-613ac480-19d2-11eb-9032-57cf6fca0a90.png)
Reilly can confirm that there should be a fourth name in the mother and father fields.

**Comment by reillyzlab** [comment]
Resolved on staging so closing.
