### ISSUE TITLE
Registry: Parents names on Marriage intention and License

### ISSUE THREAD

**Issue by jimmurphy-boston** [CityOfBoston/digital#692]
Just prior to COVID the State started switching over to below NEW
The difference is that Currently we have Name of Mother/Parent and Name of Father/Parent
We need to keep mother as the first one until we can switch to the new license - If we do not say ie Mother/Parent the couples may fill in the data and put a mother as the second parent and the father in the first - which we can do once we are able to us the CURRENT license.
The lines are just slightly different so everything is off when we print - a delicate format.
So we did get permission from the State to scan the New License in to our system and set it up so instead of printing marriage license data on to a Pre-Printed license we have the system print the image of the license as below and that data from our record right on plain perforated paper that is the correct size.
Rich had someone working on this Pre-Covid but I am not sure where it stands.
So in the mean time we need to keep Mother/Parent and then Father/Parent.
![unnamed](https://user-images.githubusercontent.com/63253451/97581836-74966180-19cb-11eb-9e11-83d3bd37dd10.png)

**Comment by reillyzlab** [comment]
Mother is currently parent 1 and father is parent 2.

Rich/Georges are the ones dealing with reworking the form. 

No work for us here so closing.
