### ISSUE TITLE
Registry: Review page - issue with residency address and odd spacing before comma

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/digital#695]
If there is no street suffix used, then there is an odd space inserted before the comma.

This space should be removed.

![Screen Shot 2020-10-30 at 11 04 07 AM](https://user-images.githubusercontent.com/20731897/97722026-2c914080-1a98-11eb-9955-f84a39614be1.png)

**Comment by phillipbentonkelly** [comment]
I think we fixed this already, seems fixed. please confirm on staging

**Comment by jimmurphy-boston** [comment]
Is fixed on Staging
