### ISSUE TITLE
Country names are submitted in Long form,

### ISSUE THREAD

**Issue by jimmurphy-boston** [CityOfBoston/digital#709]
Place of Birth is coming out LONGGGGG
With the Full State Name and UNITED STATES OF AMERICA it is taking up a lot of space.
I think USA is fine
In re to the State we may need to see how more couples fill it in and look at options.

_**After our meeting the change will be as follows:**_

**For the US**
- City: Keep the long name
- State: Use Abbreviation
- Country: Use ShortLabel if available

**Outside the US**
- City: Keep the long name
- Country: Use ShortLabel if available

**Comment by jimmurphy-boston** [comment]
![image](https://user-images.githubusercontent.com/63253451/99445588-c0159e80-28eb-11eb-80f6-2b30843def37.png)

**Comment by phillipbentonkelly** [comment]
After our meeting the change will be as follows:

**For the US**
- City: Keep the long name
- State: Use Abbreviation
- Country: Use ShortLabel if available

**Outside the US**
- City: Keep the long name
- Country: Use ShortLabel if available
