### ISSUE TITLE
Parents maiden names going in the wrong field when they go into the database

### ISSUE THREAD

**Issue by jimmurphy-boston** [CityOfBoston/digital#711]
Patty Sent screen shots and walked through the scenario.

**Comment by reillyzlab** [comment]
On person a and b of the application, Parent 1/mother is getting the maiden name meant for parent 2/father and vis versa.

This is appearing accurately on the review page but getting fed incorrectly into the database (and subsequently for the printed out certificate).

**Comment by jimmurphy-boston** [comment]
Confirmation from Patty that it has been resolved.
