### ISSUE TITLE
Access Boston- CyberARK TEST- BY Monday Feb 1, 2021

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#741]
Title: CyberArk
URL Test: https://sso-test.boston.gov/idp/startSSO.ping?PartnerSpId=PasswordVault
Status: CyberArk Users 
Security Group: SG_AB_GRPMGMT_CyberArk
Description: Privileged account management solution that deals exclusively with the protection of privileged accounts in an enterprise, including those of operating systems, databases, servers, applications, virtual machines, and networking devices
Tile (icon):  https://drive.google.com/open?id=13XbSdiQQkj_bhR1shh0DXV0kzCKKvw72&authuser=sebastian.ebarb%40boston.gov&usp=drive_fs

**Comment by andreeaursu1981** [comment]
Please update URL under tile to be:  https://zparkpvwa01.cityhall.boston.cob/PasswordVault/auth/saml

**Comment by andreeaursu1981** [comment]
Can you please change the group membership in TEST?
cn=SG_AB_CYBERARK

**Comment by andreeaursu1981** [comment]
Phil - we now created a real test environment and we will need to change the URL under the tile to be this:
https://ztarkpvwa01.cityhall.boston.cob/PasswordVault/auth/saml

**Comment by andreeaursu1981** [comment]
From https://zparkpvwa01.cityhall.boston.cob/PasswordVault/auth/saml
To: https://ztarkpvwa01.cityhall.boston.cob/PasswordVault/auth/saml

**Comment by phillipbentonkelly** [comment]
@andreeaursu1981 is this change going to the TEST environment? Just checking. Thinking of making this change alongside with the BAIS deployment tomorrow.

@mmcgowanBOS for FYI

**Comment by andreeaursu1981** [comment]
yes. this is TEST and it can be done tomorrow. Thanks so much Phil.

**Comment by phillipbentonkelly** [comment]
Ok. thanks

**Comment by andreeaursu1981** [comment]
Phil - made a mistake. The other way around. Sorry

From https://zparkpvwa01.cityhall.boston.cob/PasswordVault/auth/saml
To: https://ztarkpvwa01.cityhall.boston.cob/PasswordVault/auth/saml

**Comment by andreeaursu1981** [comment]
https://ztarkpvwa01.iam-ad-test.cob/PasswordVault/auth/saml- new URL link for TEST AB.
