### ISSUE TITLE
Access Boston TEST - HCM TEST by end of today

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#747]
Please update HCM TEST link 

From:https://baishcmtst.cityhall.boston.cob/psc/baishcmtst/EMPLOYEE/HRMS/h/?tab=DEFAULT

TO: https://baishcmtst.boston.gov/psp/baishcmtst/EMPLOYEE/HRMS/h/?tab=DEFAULT
.boston.gov

**Comment by andreeaursu1981** [comment]
TO: https://baishcmtst.boston.gov/psp/baishcmtst/EMPLOYEE/HRMS/h/?tab=DEFAULT

**Comment by andreeaursu1981** [comment]
The current Financials (PSFN) SP2 PingAccess URL domain will be changing from:
https://baisfntst.cityhall.boston.cob/psp/idmtstfn/EMPLOYEE/ERP/h/?tab=DEFAULT
.cityhall.boston.cob

To:
https://baisfntst.boston.gov/psp/idmtstfn/EMPLOYEE/ERP/h/?tab=DEFAULT

**Comment by phillipbentonkelly** [comment]
Deployed the change above to the TEST environment.

**Comment by phillipbentonkelly** [comment]
The second link is updated.
