### ISSUE TITLE
Access Boston - ScerIS PROD - MARCH 29 @ 4 PM

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#758]
**Title that needs to be under the icon on the Portal**: ScerIS 
**URL**: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=urn%3Asso%3AScerIS
**Security Group**: cn=SG_AB_Sceris
**Tile(icon)**: https://drive.google.com/drive/folders/1j4RV6uBZ3mkHGotxEoGcRTGxt5byqpjQ

**Comment by mmcgowanBOS** [comment]
Hi Andreea,
Are you requesting this change be done by 4PM on March 29? Or are you trying to time it so it's done around 4PM on that exact date. Please clarify.

Thank you.

**Comment by andreeaursu1981** [comment]
@4PM. thanks

**Comment by andreeaursu1981** [comment]
start at 4 PM. sorry.
