### ISSUE TITLE
BAIS FN update in PROD - 5/20/2021

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#761]
From (Only provides access to Bais Financials while on the CoB Network):
https://baisfn.cityhall.boston.cob/psp/prdfn/EMPLOYEE/ERP/h/?tab=DEFAULT

To (Provides access to Bais Financials Externally-Internet and internally-CoB network):
https://fn.boston.gov/psp/prdfn/EMPLOYEE/ERP/h/?tab=DEFAULT

**Comment by phillipbentonkelly** [comment]
@andreeaursu1981 is this the git issue associated with BAIS PROD deploy tomorrow (Thursday)?

@mmcgowanBOS for FYI

**Comment by andreeaursu1981** [comment]
yes sir.

From (Only provides access to Bais Financials while on the CoB Network):
https://baisfn.cityhall.boston.cob/psp/prdfn/EMPLOYEE/ERP/h/?tab=DEFAULT

To (Provides access to Bais Financials Externally-Internet and internally-CoB network):
https://fn.boston.gov/psp/prdfn/EMPLOYEE/ERP/h/?tab=DEFAULT
