### ISSUE TITLE
Access Boston tile for V3

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#767]
Title = V3
Name of the application: V3
Description of what the app is (if it is not that obvious): retirement system 
Timeline (when do you need to have live in Prod): 2 weeks
Can you please create a few designs so the Department can choose from? 

Thanks,
A

**Comment by sebastianebarb** [comment]
![Asset 18@4x](https://user-images.githubusercontent.com/20642299/113795871-df3a8e80-971b-11eb-8a46-229e044a19aa.png)
![Asset 19@4x](https://user-images.githubusercontent.com/20642299/113795872-dfd32500-971b-11eb-8a01-065a859e89fe.png)
![Asset 20@4x](https://user-images.githubusercontent.com/20642299/113795873-e06bbb80-971b-11eb-90e4-8e440d5da2a5.png)

**Comment by andreeaursu1981** [comment]
Sorry the stakeholders do not like any of them :(

**Comment by sebastianebarb** [comment]
![v3_icon-648](https://user-images.githubusercontent.com/20642299/115632557-ffe71480-a2d5-11eb-81bf-7465096e21f3.png)

**Comment by NavanK** [comment]
URL: https://sso-test.boston.gov/idp/startSSO.ping?PartnerSpId=urn%3Aauth0%3Av3locity%3Abrs-test-provider

Security Group :  SG_AB_V3

Let me know if you have any questions.

**Comment by g-grozier** [comment]
The Production Deployment date is **October 22nd.**
Here is the  PROD URL from the PM in Retirement: https://brsprod.v3locity.com/app
Security Group : SG_AB_V3

**Comment by g-grozier** [comment]
Vitech isn't able to support Single Log Out -- so in discussions about what to do (don't think 10/15 is viable date anymore).

**Comment by g-grozier** [comment]
Production Date is confirmed for **October 29th**  please scroll up for other pertinent info!

**Comment by phillipbentonkelly** [comment]
@g-grozier, @matthewcrist I think we can close this now right?

**Comment by g-grozier** [comment]
V3 was deployed ....all set!
