### ISSUE TITLE
Access Boston ServiceNow (backend application)

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#771]
Title = ServiceNow backend application
Name of the application: ServiceNow Admin 
Description of what the app is (if it is not that obvious): this application will be used now by HR as a case management system
Timeline (when do you need to have live in Prod): unknown but we need to test it in TEST

**Comment by sebastianebarb** [comment]
![user](https://user-images.githubusercontent.com/20642299/116280984-3bab2f80-a757-11eb-8a7e-b86c896105ab.png)
