### ISSUE TITLE
Access Boston enhancement- TBD - M

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#772]
When we search for users and they have more than 50 groups, we should have the ability to see the multiple pages. Let's discuss at our next monthly and see if this is a quick fix or require more dev time. 

![image](https://user-images.githubusercontent.com/49321264/116701843-61724780-a996-11eb-905d-e35a6583e81f.png)

**Comment by mmcgowanBOS** [comment]
This seems to be more of a "project". As Andreea noted, we can discuss more at the next monthly meeting.

**Comment by g-grozier** [comment]
Since no one has ever mentioned this to me, closing for now.  LAGAN is moving out of group management this spring (all being well) and that would be the major use case here.
