### ISSUE TITLE
Access Boston enhancement 2-TBD

### ISSUE THREAD

**Issue by andreeaursu1981** [CityOfBoston/digital#773]
Jira: [DIG-52 - Access Boston enhancement 2-TBD](https://bostondoit.atlassian.net/browse/DIG-52)

Add employeeID to Access Boston Group Management
![image](https://user-images.githubusercontent.com/49321264/116727410-883e7700-a9b2-11eb-9ac7-f45fe72dfa44.png)

**Comment by g-grozier** [comment]
@stephaniemar this is another thing that would still be good to do and less effort perhaps.  When can Digital provide this?
