### ISSUE TITLE
Marriage Intentions Date of appointment is set to Future date, Patty would like it  be today or in the future

### ISSUE THREAD

**Issue by jimmurphy-boston** [CityOfBoston/digital#785]
Currently its set for future date, Patty would like it to be set for todays date or future date.
![MI Date Error](https://user-images.githubusercontent.com/63253451/125461800-ae3fa088-22a9-495a-b082-722dfc43da31.png)

**Comment by phillipbentonkelly** [comment]
Fix is on Staging

**Comment by phillipbentonkelly** [comment]
@jimmurphy-boston Deployed to PROD

**Comment by phillipbentonkelly** [comment]
Can we close this? @jimmurphy-boston

**Comment by jimmurphy-boston** [comment]
We can close this
