### ISSUE TITLE
Access Boston - Service Now Tile 

### ISSUE THREAD

**Issue by NavanK** [CityOfBoston/digital#797]
Hi @phillipbentonkelly 

Access Boston Service Now Tile deployment for tomorrow 8/27/2021 from 3 to 4 PM EST.

SSO URL:  	https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fciboston.service-now.com

Security Group: cn=SG_AB_SNOWADMIN

**Comment by phillipbentonkelly** [comment]
Deploying now

**Comment by NavanK** [comment]
This is deployed and tested.
