### ISSUE TITLE
Access Boston: COVID Compliance

### ISSUE THREAD

**Issue by phillipbentonkelly** [CityOfBoston/digital#800]
TEST Environment:
-----
URL: https://cibostontest.service-now.con/covid
Security Group: cn=SG_AB_COVIDPRTL

PROD Environment:
-----
URL: 
Security Group:

**Comment by phillipbentonkelly** [comment]
@NavanK Please update this ticket when you have the info for PROD, thx

**Comment by NavanK** [comment]
@phillipbentonkelly 

Prod COVID Compliance SSO URL and Group

SSO URL: https://ciboston.service-now.com/covid
Security Group: cn=SG_AB_COVIDPRTL

**Comment by phillipbentonkelly** [comment]
Starting Covid Compliance deploy, @NavanK
