### ISSUE TITLE
Access Boston - Provide Option to Unmask a Password

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#803]
Jira: https://bostondoit.atlassian.net/browse/DIG-62

For password fields in Access Boston (at Sign In Page, when creating/updating password) include the option for the user to chose to unmask (show) the password (not have the dots).   Some sites (see screenshot) have an eye in the field.  Google just displays a checkbox below the field that says 'Show Password'.

UX will be better especially in the situations where a user has to enter a new password and confirm it again...they can compare their entries before they hit submit to make sure they match.  

![Reveal Password](https://user-images.githubusercontent.com/91092683/134066230-22c59216-3a3f-4f54-9b42-912b35ac92b4.png)

**Comment by rachelsater** [comment]
@g-grozier Hi, is this something you still want us to work on? If yes, I'll move this ticket to the backlog

**Comment by g-grozier** [comment]
Yes, anything open is work that still needs to be done.
