### ISSUE TITLE
AccessBoston Portal icon - ServiceNow and Banner

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#806]
There are 3 tasks as part of changes on 12/13: deploy new Beacon app, deploy banner on ABP to announce Beacon launch, and change the icon/label on ServiceNow.  Caroline put the 2 new icons in the folder.

**Deploy Beacon**
Icon = lighthouse  
Position of Icon = top left (so the place where ESS used to be, pole position)
Name of the application = Beacon
URL for PROD = https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fciboston.service-now.com/cob
Timeline (when do you need to have live in Prod): **12/13 after hours (after 5pm)*** 
Group = ALL EMPLOYEES (like ESS, it's a birthright for employees)
At go-live the Beacon app should be seen by all employees (do not include sponsored accounts)
This is the customer-facing app (as opposed to the backend/admin one)

**Deploy Banner**
Also deploy the Access Boston Portal banner with this language: **Beacon, the new HR self-service portal, is now live!** Look for the lighthouse icon below. 

**Update ServiceNow**
Change the ServiceNow icon's label to be 'ServiceNow - Lightkeeper'
Update icon to the person at the helm (ship's wheel)

**Comment by g-grozier** [comment]
Please deploy the banner in Dev and/or Test no later than 12/8 -- so we can confirm we still have that functionality/option and can show it to the customers to make sure it is what they want. @phillipbentonkelly @stephaniemar

**Comment by phillipbentonkelly** [comment]
Icons on Assets site
- [Lightkeep](https://assets.boston.gov/icons/accessboston/ship_wheel.svg)
- [Beacon](https://assets.boston.gov/icons/accessboston/lighthouse.svg)
- [Helm Icon](https://assets.boston.gov/icons/accessboston/helm.svg)

**Comment by phillipbentonkelly** [comment]
@g-grozier is Beacon using the same `groups` as ServicesNow - Lightkeeper? If not could you update here with the group for it.

Thx

**Comment by phillipbentonkelly** [comment]
@g-grozier Also, will we get URLs for the `DEV|TEST` environments? The only URL here is for PROD.

**Comment by g-grozier** [comment]
@phillipbentonkelly updated with group info.  It's already been done in Dev and Test (I think waaay back like in February maybe?)

**Comment by g-grozier** [comment]
Just confirming it's NOT the same group as Lightkeeper, these are different
apps (sort of).




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by g-grozier** [comment]
Dev URL for Beacon: https://cibostondev.service-now.com/cob
Test URL for Beacon: https://cibostontest.service-now.com/cob
Prod URL for Beacon: https://ciboston.service-now.com/cob

The distinction between the Lightkeeper and Beacon sections of SNOW is the /cob appended at the end (for Beacon). @phillipbentonkelly

**Comment by stephaniemar** [comment]
I reviewed all the tickets and got some questions answered so I have a better understanding of what the Digital Team is responsible for leading up to Beacon going live next week, here is my understanding: 

12/7-8:
@phillipbentonkelly is going to 
1. Deploy the Lighthouse icon onto the Access Boston test environment and link it to the Beacon app Test Environment (https://cibostontest.service-now.com/cob)
2. Add the Banner language to Access Boston test environment 
3. Replace the current ServiceNow label to 'ServiceNow - Lightkeeper' with new Helm Icon on the Access Boston TEST Environment 

12/13 - for Go Live 12/14
@phillipbentonkelly is going to 
1. Deploy the Lighthouse icon onto Access Boston PROD and link it to the Beacon PROD Environment (https://ciboston.service-now.com/cob) assigned to Group = ALL EMPLOYEES
2. Add the Banner language to the Access Boston PROD environment 
3. Replace the current ServiceNow label to 'ServiceNow - Lightkeeper' with new Helm Icon on the Access Boston PROD Environment 

Let me know if this is correct @g-grozier 
@phillipbentonkelly Let me know if there are any blockers or if I can clarify anything. 

cc @mmcgowanBOS

**Comment by phillipbentonkelly** [comment]
Thanks for the clarification @stephaniemar

**Comment by g-grozier** [comment]
This is a great summary - in deploying Beacon it's also setting the group
that sees it to ALL EMPLOYEES




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by phillipbentonkelly** [comment]
@g-grozier, Just a point of clarification, because this is something we had to go back-n-forth with Andreea, `birthright` access means its visible to all ... if that's the case the way the app does that is by not adding a `group` to the application. Does that make sense? It would explain why I thought I should be getting a group for Beacon but none has come through.

**Comment by g-grozier** [comment]
The group is ALL EMPLOYEES - it is the same set-up as ESS. It's a
birthright for employees (but not those with a sponsored account).

**Comment by phillipbentonkelly** [comment]
I looked at ESS (Employee Self-Service) and it has the group `SG_AB_ESS`, so is this the group you want us to put on Beacon?

**Comment by stephaniemar** [comment]
12/8

1. Deploy the Lighthouse icon onto the Access Boston test environment and link it to the Beacon app Test Environment (https://cibostontest.service-now.com/cob) -**Complete**
2. Add the Banner language to Access Boston test environment- **Complete**
3. Replace the current ServiceNow label to 'ServiceNow - Lightkeeper' with new Helm Icon on the Access Boston TEST Environment --- **Complete**

**Comment by g-grozier** [comment]
it was done!  To see use 050994 to log into Test.

[image: Screenshot 2021-12-08 142624.png]




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by stephaniemar** [comment]
I see it now- Perfect!

**Comment by stephaniemar** [comment]
This work was completed 12/13 by @phillipbentonkelly
