### ISSUE TITLE
Access Boston - integrate Avolve Test

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#807]
![Avolve icon](https://user-images.githubusercontent.com/91092683/136971263-bc1b233d-f0f9-4556-8e56-da00e27cbce1.png)

Name = Avolve
URL Test = http://boston-ma-us-test.avolvecloud.net/Portal/
Group = SG_AB_Avolve
icon okayed by Kelly

should be up in Test by end of October (for UAT)

**Comment by phillipbentonkelly** [comment]
@g-grozier did we get this icon from the Design team? We need the version that's transparent, right size, etc.

**Comment by g-grozier** [comment]
Yes, I got it from Sebastian  He said it's in the same folder as always.




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by phillipbentonkelly** [comment]
Ok, i found it thx

**Comment by mmcgowanBOS** [comment]
Gretchen, what day would you like this to be pushed to the Dev environment?

**Comment by g-grozier** [comment]
anytime is good, I'm not sure ISD is ready to Test but we can do a smoke
test in Dev and move it to Test (in preparation for their UAT)

**Comment by phillipbentonkelly** [comment]
@g-grozier, @matthewcrist  I'd take we need a DEV specific URL for the icon, the one we have is for TEST

**Comment by g-grozier** [comment]
They only have the single no-Prod environment.  So please set up Dev and
Test ABP to point to that... G.

**Comment by g-grozier** [comment]
Is this work done?  We haven't actually integrated Ping TEST with Avolve
TEST yet....

**Comment by stephaniemar** [comment]
Sorry-- we are doing some clean up and this looked like an old ticket. I can re-open. So where are we with this, do you know? Do we need to finish?

**Comment by g-grozier** [comment]
The vendor (Avolve) cannot support single logout -- so this app will be intergrated with Access Boston but NOT be on the Portal. Closing out this ticket

**Comment by stephaniemar** [comment]
@phillipbentonkelly @davidrkupton Just FYI -- this one has been closed
