### ISSUE TITLE
deploy Tableau Icon on Test and Dev AB

### ISSUE THREAD

**Issue by NavanK** [CityOfBoston/digital#817]
Test Tableau URL: https://sso-test.boston.gov/idp/startSSO.ping?PartnerSpId=http%3A%2F%2FzTTableau02

Dev Tableau URL: https://sso-dev.boston.gov/idp/startSSO.ping?PartnerSpId=http%3A%2F%2FzDTableau01

Security Group: cn=SG_AB_TABLEAU

Group Management Group: cn=SG_AB_GRPMGMT_TABLEAU

**Comment by NavanK** [comment]
Completed.

**Comment by g-grozier** [comment]
this was completed and confirmed by app owner (Data Analytics)
