### ISSUE TITLE
Make Access Boston Portal findable in web search

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#824]
Jira: https://bostondoit.atlassian.net/browse/DIG-59

In talking with BPS Help Desk, their less tech-savvy users have a hard time typing in the URL of ABP (!!)  They asked to allow it to come up in a Google Search...which is fine, it's password protected.

@JamesDuffy said: My guess is that there's some "noindex" and "nofollow" meta tagging being added to the actual portal page. Since it's a password protected website, maybe the intention was for the public to never find it.

Who do you work with on updating the portal page? Is that Phil or David? If you want to make it indexable, I think they would just need to adjust that in the metadata.

Please confer with James on what needs to happen and make the ABP indexable asap

**Comment by jamesduffy** [comment]
Hello Boston Friends 👋 and fellow James Duffy. I am not the James Duffy you spoke with, but I agree with what your James said. I will turn this over to @duffy-james.

I will also use this opportunity to ask you to please support wgbh and This Old House. Thank you.
