### ISSUE TITLE
HOLD: Banner for Beacon Launch/Changes

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#825]
For the Beacon launch we will deploy the banner on Access Boston Portal and then update several times for the various changes.  I'm putting all the text here but will also include in the individual issues for each change.

_Launch banner_
10/14: **Beacon, the new HR self-service portal, is now live!** Look for the lighthouse icon below.

_Days before ESS goes_
Jan TBD: NOTICE: The Employee Self-Service tile will be moving under the Beacon portal on January xx, 2022.

_Once ESS is removed_
Jan TBD:  **Looking for Employee Self-Service? It's moved to the Beacon portal**! To access ESS, click on the lighthouse icon below.
idea from Liz -- change the label on the Beacon icon to Beacon (ESS) for the first little while too

**Comment by stephaniemar** [comment]
I see two tickets for this work #806 and #825 what is the difference. Just so I am clear we need the new banner and language deployed on Dev so we can get approval? @phillipbentonkelly is that your understanding as well?

**Comment by g-grozier** [comment]
as noted in 825 - I wanted to make sure we had each of the 3 upcoming
banner texts in one place. But I'll put the  banner wording in as a step
for each of the various deployments.

806 is for Beacon launch
there will be a new issue for the removal of ESS in mid-January.  And I can
do one for the interim banner deployment too.  G.




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by stephaniemar** [comment]
Hi @phillipbentonkelly here are the requirements for the banner on Test
NOTICE: **Beacon, the new HR self-service portal, is now live!** Look for the lighthouse icon below.

1. Notice should be in all CAPs
2. Lead sentence should be in Bold
3. Whole sentence should be top justified. 

cc @g-grozier

**Comment by stephaniemar** [comment]
Banner was updated on Test 12/8

**Comment by stephaniemar** [comment]
@g-grozier I cannot remember is there a reason we are keeping this open?

**Comment by g-grozier** [comment]
OHR had said they were going to make the updates for these 2 changes "in
January".
I think with additional COVID compliance they are underwater again.  So we
can close and re-open when they (if they) move ahead with changes. G.




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by g-grozier** [comment]
Before closing a ticket, please confirm if the work has been completed.  OHR is still planning on doing this...just not sure when

**Comment by rachelsater** [comment]
Sorry I thought your comments from Jan 26 implied the work was completed.
