### ISSUE TITLE
Remove Banner from Access Boston Portal

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#840]
Please remove the following banner from the Access Boston Portal

NOTICE: Beacon, the new HR self-service portal, is now live! Look for the lighthouse icon below.

**Comment by stephaniemar** [comment]
Hey @phillipbentonkelly -- added this per @g-grozier request. When you get a chance can you let us know when this can be done. Thanks!

**Comment by phillipbentonkelly** [comment]
Deploying change this morning

**Comment by stephaniemar** [comment]
@g-grozier -- Banner will be removed this morning. Thanks @phillipbentonkelly

**Comment by stephaniemar** [comment]
All Set -- Banner is gone from ABP
