### ISSUE TITLE
put Cyberark onto Access Boston Portal

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#847]
timeframe for rollout is March 1
Small set of internal (DoIT) users so can be anytime of the day
Icon done already (another lock)
Will get you the Prod URL shortly
And the security group who will see this icon

**Comment by stephaniemar** [comment]
Hi @phillipbentonkelly -- Can you take a look at this and assess how much time this will take so we can schedule it for the 3/1 launch. Also, let me know if you have questions, and if you need anything to complete this. 

cc @davidrkupton

**Comment by phillipbentonkelly** [comment]
@stephaniemar this would take about an +1hour per deployment, I see no mention here of this being tested on their DEV/TEST environments. We should get a confirmation if they're doing that and what the URLs for those would be. Below are the fields we should always get from them. 

- title [required]
- URL [required]
- icon
- groups [depends]

**Comment by stephaniemar** [comment]
@phillipbentonkelly security group for this is the following --SG_AB_CyberArk. I am following up with Gretchen on the other questions.

**Comment by stephaniemar** [comment]
Cyberark icons 
![password (1)](https://user-images.githubusercontent.com/92751818/152429935-3835cd1f-fee6-4e92-9324-486e648c111c.svg)
![password](https://user-images.githubusercontent.com/92751818/152429937-4b412ddd-4422-4d6b-9c39-1a8705768c45.png)
 
cc @phillipbentonkelly @davidrkupton

**Comment by g-grozier** [comment]
their is no Dev environment for Cyberark.  Test environment details are on this sheet https://docs.google.com/spreadsheets/d/1OiH2HBLE55X8MzGaB7H9VC_a2WpQQcjV4-eyNpJGTPY/edit?usp=sharing

I have seen the icon on Dinesh's screen so I think it was deployed (it would have been beginning of pandemic timeframe)

**Comment by stephaniemar** [comment]
Cyberark information: 

NOTE: There is no Dev Environment

**title** 
Cyberark
**URL** 
Test: https://sso-test.boston.gov/idp/startSSO.ping?PartnerSpId=PasswordVault
Prod: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=PasswordVault
**icon**
See icon in comment above 
**groups**
Test: SG_AB_CyberArk
Prod: SG_AB_CyberArk

**Comment by stephaniemar** [comment]
Hi -- I just confirmed the following with Gretchen (@g-grozier) 

1. This is already on Test and has been tested - Dinesh confirmed. 
2. We just need to deploy to prod on March 1st - we can do Feb 28 
3. I will submit a Change request form for the deployment a week before March 
(https://app.smartsheet.com/b/form/da53144d80704598bf297e4b5d98d67b)

@phillipbentonkelly let me know if you have any questions.

**Comment by stephaniemar** [comment]
@phillipbentonkelly @davidrkupton -- I filling out the Change Management form for the Cyberark work. I need to put in a start and end date. Should we schedule to do this Monday 2/28, so it is available 3/1?

**Comment by davidrkupton** [comment]
I think the ticket just needs to note the time the change will be affected,
which is a duration of 20mins at whatever time we agree with Gretchen we
put this live on 3/1 or 2/28.

On Tue, Feb 22, 2022 at 12:06 PM stephaniemar ***@***.***>
wrote:

> @phillipbentonkelly
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_phillipbentonkelly&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=EIsJrhuoiDDOOG9zT5Qhxh549JCCN2EumK88MvVgrPI&s=9pup8PAkq_Z-taYI3yVZ462sb-NIggnfpHdlX6ZyOOE&e=>
> @davidrkupton
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_davidrkupton&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=EIsJrhuoiDDOOG9zT5Qhxh549JCCN2EumK88MvVgrPI&s=G9TUzSzCWwSQISRArk3Zz2KsbIVC33EP8moY2BzsJ2w&e=>
> -- I filling out the Change Management form for the Cyberark work. I need
> to put in a start and end date. Should we schedule to do this Monday 2/28,
> so it is available 3/1?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CityOfBoston_digital_issues_847-23issuecomment-2D1048017327&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=EIsJrhuoiDDOOG9zT5Qhxh549JCCN2EumK88MvVgrPI&s=JWEZz2q1sJR00ExnjNz4zt1f5ffV6wiEXrbintc4llk&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABD3PEUC6Y2XN2YJZDJYTH3U4O7CZANCNFSM5MZCYC3Q&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=EIsJrhuoiDDOOG9zT5Qhxh549JCCN2EumK88MvVgrPI&s=Bt5ff3I1s_rL4HPo_gPza8iz-Dg5JVY9Uvxs6_8uGDQ&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=EIsJrhuoiDDOOG9zT5Qhxh549JCCN2EumK88MvVgrPI&s=UIljfL8bCvgCbBrbbzVZ7iG4T5aoQNEInr8JW8RpeEg&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=EIsJrhuoiDDOOG9zT5Qhxh549JCCN2EumK88MvVgrPI&s=X9Wno8Ytmzui2-CdQtlcxfp_UVfrSvxPLnEtbNfODiA&e=>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 

[image: COB_B_Blue_square-01.png]

David Upton

Digital Team / Operations Team

Department of Innovation and Technology

781 330 5041 (c)

**Comment by g-grozier** [comment]
how precise can I go ..... 3:26pm on 2/28?
In all seriousness, we are launching this tool with the LAN team as the
pilot group so anytime on 2/28 or 3/1 would be good.
If we can aim for prior to noon on 3/1 -- that will give us time to confirm
with the pilot group they can see the icon/access the app.

Thank you!  G.

**Comment by stephaniemar** [comment]
I talked to Phil and I put after 3:30 on 2/28, that way it is there in the morning of 3/1

**Comment by stephaniemar** [comment]
Linking the Portal Access Sheet here: https://docs.google.com/spreadsheets/d/1OiH2HBLE55X8MzGaB7H9VC_a2WpQQcjV4-eyNpJGTPY/edit#gid=0

**Comment by phillipbentonkelly** [comment]
@g-grozier, the deploy is done.

**Comment by g-grozier** [comment]
Thanks - I have confirmation from two pilot users that they can see it.
