### ISSUE TITLE
Remove Boston Gives Back icon from Access Boston Portal

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#848]
The Treasury Department just let us know they are decommissioning use of _Boston Gives Back_. The app is no longer active/accessible.  We will remove it from the IAM systems but also need to take it off the ABP as well.

Sooner the better....since anyone who clicks on it goes nowhere

**Comment by stephaniemar** [comment]
Hey @phillipbentonkelly -- how long will something like this take. David, James and I met yesterday and we are hoping to knock to off the list for Gretchen.

**Comment by phillipbentonkelly** [comment]
@stephaniemar this would take about an hour to remove, let me know when you want it removed

**Comment by stephaniemar** [comment]
Ok sound good @phillipbentonkelly I would say if you need a break from the Node work pick this up.
Let me know when you pick it up so I can send an update. 
cc @davidrkupton

**Comment by phillipbentonkelly** [comment]
Ok, I'll probably do it after our 2 pm meeting about Assessing.

**Comment by stephaniemar** [comment]
@phillipbentonkelly Thanks, we do not have any one looking at this, I did update anyone that it was going to be done today. I can reach out to IAM once it is on test first to take a look. Just let me know. Also, I think David is trying to get me access to the environments so I can help moving forward.

**Comment by phillipbentonkelly** [comment]
@stephaniemar this change is now on PROD, I don't think I'm in the group for this so I don't see the icon either way but ABP team can verify.

cc @davidrkupton

**Comment by stephaniemar** [comment]
Thanks @phillipbentonkelly -- @g-grozier can you check this on your side? Thanks.

**Comment by g-grozier** [comment]
Icon is gone!  Thanks for the speedy turnaround.
