### ISSUE TITLE
Identify Verification Link from ABP

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#852]
As a user I will see a Confirm ID badge on the Access Boston Portal, when clicked it will start the ID Verification process for non- integrated apps.

- [ ] New Badge will have the name Confirm ID
- [ ] When the new Confirm ID icon is clicked the user will start the new ID Verification Workflow for non- integrated apps

**Comment by g-grozier** [comment]
have an icon from Caroline: 
![badge icon](https://user-images.githubusercontent.com/91092683/160677003-92c8952a-e16f-4135-a6c0-a2b35c55db6f.svg)

**Comment by g-grozier** [comment]
![id_badge](https://user-images.githubusercontent.com/91092683/160680782-8800af32-b5c8-41b7-8a23-0edf592efa91.svg)

**Comment by g-grozier** [comment]
@phillipbentonkelly I asked for new URLs for this process and Frank said "EXTERNAL records: I'll need to know the public IP or CNAME to point to".  Can you provide the CNAME/IP please?  For Test and Prod.

**Comment by g-grozier** [comment]
@phillipbentonkelly here are the URLs that Sam just sent:
Dev - [http://zdiiqtk01:8086/identityiq](https://urldefense.proofpoint.com/v2/url?u=http-3A__zdiiqtk01-3A8086_identityiq&d=DwMFaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=aesSyTKyBo1wXq0uHcul0Feqg6FKycBjrxbfUZS7AMA&m=AzswvUfzP7hhlAPGzip2uX-CdJ_vq1dJ9T6EaRnwJco&s=sfic4w-WcMgaZanS4aGpznBWMd9YJk0wijZRVs4Slvg&e=)

Test- [http://sailpoint-test.cityhall.boston.cob:8086/identityiq](https://urldefense.proofpoint.com/v2/url?u=http-3A__sailpoint-2Dtest.cityhall.boston.cob-3A8086_identityiq&d=DwMFaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=aesSyTKyBo1wXq0uHcul0Feqg6FKycBjrxbfUZS7AMA&m=AzswvUfzP7hhlAPGzip2uX-CdJ_vq1dJ9T6EaRnwJco&s=LGk96Yum6qE3lBCDulWa_FPWFU9KWgAnRDNJvwL2bqA&e=)

Prod - [http://sailpoint.cityhall.boston.cob:8086/identityiq](https://urldefense.proofpoint.com/v2/url?u=http-3A__sailpoint.cityhall.boston.cob-3A8086_identityiq&d=DwMFaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=aesSyTKyBo1wXq0uHcul0Feqg6FKycBjrxbfUZS7AMA&m=AzswvUfzP7hhlAPGzip2uX-CdJ_vq1dJ9T6EaRnwJco&s=ZPrGp_8jCM7zPuMkVxl3wAEwxy2sNUTY10gFriFXyBY&e=)

**Comment by phillipbentonkelly** [comment]
@g-grozier I emailed this, putting here too for ref.

Checking out those endpoints they return 401 'no access' errors for DEV & PROD. Is this happening because `BASIC AUTH` credentials (username/password) are different for each of them and what we have is the user/pass for just TEST?

### DEV
![unnamed](https://user-images.githubusercontent.com/2627273/161331971-abf0c173-dee1-4717-ad4c-5a8744506f5e.png)

### TEST

![unnamed](https://user-images.githubusercontent.com/2627273/161332126-641113e5-caa0-48b2-a0e8-ff09aaddbcaf.png)

btw, the new URL for TEST works.

**Comment by g-grozier** [comment]
My team doesn't work in Digital GitHub.  @phillipbentonkelly if you have questions you can either email (which I believe you did) or better yet set up a quick meeting.

**Comment by rachelsater** [comment]
Thanks Gretchen! Phil emailed the team the same info last Friday.

**Comment by rachelsater** [comment]
@g-grozier can you please let us know the group name? thanks

**Comment by g-grozier** [comment]
It's on the Portal Content sheet. Can you all please look at the
requirements doc - which is how we make sure reqs are captured?
https://docs.google.com/spreadsheets/d/1OiH2HBLE55X8MzGaB7H9VC_a2WpQQcjV4-eyNpJGTPY/edit?usp=sharing

SG_AB_CONFIRMID
