### ISSUE TITLE
Update to Cyberark link (should be https://pam.boston.gov/)

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#874]
We provided the SP initiated link to you not the IDP one.  Please update icon to point to https://pam.boston.gov/

**Comment by stephaniemar** [comment]
@phillipbentonkelly @davidrkupton --- Hey-- We need to update the Cyberark URL-- we were giving the wrong one by mistake . Is this an easy update?

**Comment by phillipbentonkelly** [comment]
@stephaniemar it is, when do we need to do it

**Comment by stephaniemar** [comment]
@phillipbentonkelly We should probably do it today so the users go to the right place when they click the icon.

**Comment by phillipbentonkelly** [comment]
@stephaniemar deployed

**Comment by stephaniemar** [comment]
Thanks @phillipbentonkelly. @g-grozier This should be all set now.
