### ISSUE TITLE
Access Boston - Tanium

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#875]
New application = Tanium
Endpoint management tool
Icon requested on 3/8
SG_AB_TANIUM

URL for **TEST** = boston.cloud.tanium.com

**Comment by stephaniemar** [comment]
Icon
![Tanium](https://user-images.githubusercontent.com/92751818/157466705-250960cc-6962-4761-ab80-ee90079ee7af.png)

**Comment by stephaniemar** [comment]
@phillipbentonkelly @davidrkupton this just came in from Access Boston -- Is this something we can do today? It needs to go onto test.

**Comment by g-grozier** [comment]
![secure svg](https://user-images.githubusercontent.com/91092683/157476284-3ad63d3d-45e2-4984-96ea-a6df5dea5b30.png)
this is SVG

**Comment by davidrkupton** [comment]
@stephaniemar I'm fine if its a small job. Phill could do with a break from registry...

**Comment by stephaniemar** [comment]
@davidrkupton Sounds Good @phillipbentonkelly let me know your timing and then we can update Access Boston Folks.

**Comment by phillipbentonkelly** [comment]
@stephaniemar I can deploy staging (TEST) tomorrow

**Comment by stephaniemar** [comment]
@phillipbentonkelly Ok, sounds good. Will you be able to squeeze in https://github.com/CityOfBoston/digital/issues/876 while you are doing that?

**Comment by stephaniemar** [comment]
@phillipbentonkelly Any updated on these tickets? Can I move them to done?

**Comment by phillipbentonkelly** [comment]
@stephaniemar gonna deploy them at 2pm

**Comment by phillipbentonkelly** [comment]
Deploy (TEST) is done

**Comment by g-grozier** [comment]
@phillipbentonkelly Phil C reports The Tanium Tile points to the wrong address:
It points to https://access-test.boston.gov/boston.cloud.tanium.com
It should point to https://boston.cloud.tanium.com/
Please fix!

**Comment by phillipbentonkelly** [comment]
fix deployed

**Comment by stephaniemar** [comment]
@g-grozier Can you or someone test quickly to make sure it is all set.

**Comment by g-grozier** [comment]
Phil C reports the Tanium tile on Test Portal is now working...

**Comment by stephaniemar** [comment]
Great. I will close this and mark it as done

**Comment by stephaniemar** [comment]
@rachelsater Closing this ticket but there will be a similar request next week for this to move to Prod.
cc @phillipbentonkelly @davidrkupton
