### ISSUE TITLE
Access Boston- FHE Salesforce

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#876]
app name = FHE Salesforce   [FHE stands for Fair Housing & Equity]
icon = house option 1  [asked Caroline for svg version]
![House Option 1](https://user-images.githubusercontent.com/91092683/157511002-2c93eafe-703b-453e-acf8-93911fb7e0d2.png)
TEST URL = https://cob--uat.my.salesforce.com/
Group = SG_AB_FHESALESFORCE

**Comment by g-grozier** [comment]
![house_2](https://user-images.githubusercontent.com/91092683/157512282-547c9510-38a4-4917-9664-59455da45380.svg)
SVG version

**Comment by stephaniemar** [comment]
@phillipbentonkelly Here is another one for the Test environment if you have time while you are updating it with the other ticket. 

@davidrkupton

**Comment by phillipbentonkelly** [comment]
@stephaniemar I can do both tomorrow

**Comment by g-grozier** [comment]
Prod URL will be cob.mysalesforce.com

**Comment by stephaniemar** [comment]
@g-grozier This only needs to go on Test for now though, correct? Phil said he will be able to deploy both Icons tomorrow.

**Comment by g-grozier** [comment]
Yes, just to TEST -- we have both groups on standby to test there ....so
Prod deploy maybe next week? or week after

**Comment by phillipbentonkelly** [comment]
Deploy is done

**Comment by stephaniemar** [comment]
@g-grozier Does this one look good?

**Comment by g-grozier** [comment]
Test users all say it is good.
Will coordinate a Prod go-live date with them next week. G.

**Comment by stephaniemar** [comment]
Great. Will close this ticket

**Comment by stephaniemar** [comment]
@rachelsater Closing this ticket but there will be a similar request next week for this to move to Prod. 
cc @phillipbentonkelly @davidrkupton
