### ISSUE TITLE
Deploy Tanium to PROD

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#877]
On Thursday 3/17 add the Tanium icon to Production
URL = https://boston.cloud.tanium.com
Group = SG_AB_TANIUM

**Comment by phillipbentonkelly** [comment]
PROD Deploy @4pm 3/17

**Comment by phillipbentonkelly** [comment]
@g-grozier I usually do PROD deploys at 4pm on the day of. I see in my calendar a meeting for 9AM tomorrow for this, if the intention is for the deploy to be done/ready for tomorrow AM then I need to deploy EOD today. Can you clarify when?

cc'd: @davidrkupton, @rachelsater

**Comment by phillipbentonkelly** [comment]
@g-grozier, @rachelsater deploy is done.

**Comment by g-grozier** [comment]
emailing Phil to check it out. Thanks Phill

**Comment by g-grozier** [comment]
Phil says he doesn't see the Tanium group to manage...he has the right
group in FID.  Is that a Portal thing (you need to set it up somehow)?
SG_AB_GRPMGMT_TANIUM

[image: Cheetham.png]

**Comment by phillipbentonkelly** [comment]
When we found the issue on the TEST environment, was he able to see and edit groups after he was added to the mgmt-group (SG_AB_GRPMGMT_TANIUM)?

**Comment by g-grozier** [comment]
Yes...but he's not seeing in Prod despite being in that group (GRPMGMT)

**Comment by phillipbentonkelly** [comment]
On PROD, is he `also` in the `SG_AB_TANIUM` group? He needs both

- SG_AB_TANIUM - Let's you see the icon/link
- SG_AB_GRPMGMT_TANIUM - Let's you manage the group

**Comment by g-grozier** [comment]
![Cheetham](https://user-images.githubusercontent.com/91092683/159025741-0bbbc315-dabc-47e2-b3c2-61f7100e6a24.png)

**Comment by g-grozier** [comment]
please look at the screenshot I included

**Comment by phillipbentonkelly** [comment]
taking a look

**Comment by phillipbentonkelly** [comment]
@g-grozier I look him up by ID on the PROD and endpoint and he is those two groups. I am able to see to see on the TEST environment (code is the same), I restarted the PROD servers, can you ask him to check again and look for the [logo](https://assets.boston.gov/icons/experiential_icons/secure.svg). Is there anybody else I can lookup (PROD) that is also on that group, could you pass along a couple employee numbers

**Comment by g-grozier** [comment]
3 people in that group:
Alex T   145645
Rashad 133406
Phil C 116191

each should be in SG_AB_TANIUM and SG_AB_GRPMGMT_TANIUM.
No probs with login, just group management

**Comment by phillipbentonkelly** [comment]
Can Alex and Rashad see the icon? Does link work for them if they can see it.

**Comment by g-grozier** [comment]
Rashad left early (something with his car).  Alex is working from home I
think, but I'll chat him

I think if they could not see it we'd have heard for sure!

**Comment by g-grozier** [comment]
Alex can see the Tanium icon and access the app

**Comment by g-grozier** [comment]
Alex is good for Group Management too (Phil C must have weird data or
something)

**Comment by phillipbentonkelly** [comment]
Ok, can we close this ticket then
