### ISSUE TITLE
Update ESS tile on DEV Access Boston Portal to the new cloud URL

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#878]
[DIG-51 - Update ESS tile on DEV Access Boston Portal to the new cloud URL](https://bostondoit.atlassian.net/browse/DIG-51)

Can we make the ESS tile in the Development environment of the ABP point to the cloud version (post upgrade) please?  

https://ess-awsdev.boston.gov

We want to do a little smoke testing there if possible

**Comment by rachelsater** [comment]
@g-grozier Can we please discuss this ticket in today's meeting? We would like more clarification on the testing and when this needs to be ready for your team.

**Comment by stephaniemar** [comment]
@g-grozier do you know if this was every done- Post Upgrade?(BAIS)?

**Comment by ggrozierBOS** [comment]
No idea, will ask @DineshBaddam to check on it...

**Comment by ggrozierBOS** [comment]
@DineshBaddam confirms it's https://ess-awsdev.boston.gov/ -- so good and closing!

**Comment by stephaniemar** [comment]
@g-grozier great, thanks.
