### ISSUE TITLE
FHE Salesforce to Prod 3/28

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#881]
By start of day 3/28 add the FHE SF icon to Production  [house]
URL = https://cob.my.salesforce.com
Group = SG_AB_FHESALESFORCE

**Comment by phillipbentonkelly** [comment]
@g-grozier my schedule now is from 10am-6pm ... I can deploy this either EOD 3/25 or 10AM 3/28

@rachelsater

**Comment by g-grozier** [comment]
this just has to be ready for 9am on 3/28 but you can start late afternoon
on 3/25
Or if you want to do it in your jammies over the weekend that works too!
 : )

**Comment by phillipbentonkelly** [comment]
Ok, I'll deploy it EOD 3/25 👍

**Comment by phillipbentonkelly** [comment]
deployed

**Comment by g-grozier** [comment]
the date was March 28th, please remove from Prod

**Comment by g-grozier** [comment]
@phillipbentonkelly Hi, we got the wrong URL for Prod - it's [https://cob.my.salesforce.com](https://cob.mysalesforce.com/)
there is a period between the my and the salesforce.  Can you add that in before Monday morning pls?  (Sorry!!)

**Comment by phillipbentonkelly** [comment]
@g-grozier @rachelsater change is deployed

**Comment by g-grozier** [comment]
Looks good, thanks you
