### ISSUE TITLE
ESS tile in TEST Access Boston Portal is directing to PROD environment

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/digital#882]
Jira: https://bostondoit.atlassian.net/browse/DIG-61

the ESS tile seems to be using ess.boston.gov (the Production environment) - should be going to a TEST environment?

**Comment by rachelsater** [comment]
@g-grozier This was a draft ticket. Is this an issue for us to work on?

**Comment by g-grozier** [comment]
I was told to put things into the Project and once the DIgital team had
discussed they would move it into an issue.
Please just clarify what process you need me to follow -- happy to do
whatever but the constant changing is a bit hard to manage

**Comment by rachelsater** [comment]
Gotcha. Sorry I didn't know that was the process. it's all good

**Comment by stephaniemar** [comment]
@g-grozier do we have a test URL for ESS. I just looked at this and the ESS Link  in Test is directing folks to PROD.

**Comment by ggrozierBOS** [comment]
@NavanK what should the TEST ESS (AWS) URL be ...on Access Boston Portal, pls?

**Comment by NavanK** [comment]
Here is the Test ESS url: https://ess-awsuat.boston.gov

**Comment by stephaniemar** [comment]
@NavanK Thanks!
