### ISSUE TITLE
Need to redirect redirect RentSmart application

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/digital#883]
We need to redirect rentsmart.boston.gov (resolving to https://rentsmart.boston.gov/index.html) to this url:

https://data.boston.gov/dataset/rentsmart

For our records, as of March 21, 2022:
rentsmart.boston.gov currently --- CNAMEs to --- rentsmart.boston.gov.herokudns.com

@davidrkupton discussed the possibility of redirecting to Drupal, and then redirecting from Drupal to the dataset.

**Comment by davidrkupton** [comment]
OK so my plan is:
- [ ] Use the [redirect_domain](https://www.drupal.org/project/redirect) sub-module of [redirect module](https://www.drupal.org/project/redirect) already installed.
- [ ] enable on Acquia `dev`
- [x] ask Frank to register a new subdomain `jd.boston.gov` and redirect CNAME to **d8-dev.boston.gov**
- [ ] On Acquia Cloud portal, register **jd.boston.gov** as a domain for the `develop` environment
- [ ] in the domain_redirect module in Drupal, add a new redirect from **jd.boston.gov** to **rentsmart.boston.gov**
- [ ] test (on dev)
- [ ] if it works then ask Frank to delete **jd.boston.gov** and update the `rentsmart.boston.gov` subdomain to point to **boston.gov** (CNAME)
- [ ] in Drupal on ACquia dev environment, delete **js.boston.gov** 
- [ ] in Drupal on prod environment, enable redirect_domain and then create new redirect for **rentsmart.boston.gov** to **https://data.boston.gov/dataset/rentsmart**

**Comment by duffy-james** [comment]
@davidrkupton Frank has registered a new subdomain jd.boston.gov and redirected CNAME to d8-dev.boston.gov

**Comment by davidrkupton** [comment]
OK we can look at this tomorrow.

On Tue, Mar 22, 2022 at 2:53 PM James Duffy ***@***.***>
wrote:

> @davidrkupton
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_davidrkupton&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=zAyaBwAgbSBe1hU7ASyHI5-pKxIeCQdtumi3F0Ld7J4&s=Mqqw3eL2RJrWzBE3AnxADSvTFeTVZzWSPpREjL8E_mU&e=>
> Frank has registered a new subdomain jd.boston.gov and redirected CNAME
> to d8-dev.boston.gov
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CityOfBoston_digital_issues_883-23issuecomment-2D1075514569&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=zAyaBwAgbSBe1hU7ASyHI5-pKxIeCQdtumi3F0Ld7J4&s=0pMctk48WFTe0JRVWVeL-TKW0Iufjxlrbu6gLtDID-4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABD3PEVKXDNSGYXB4RG4DHLVBIJLPANCNFSM5RIBLL5A&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=zAyaBwAgbSBe1hU7ASyHI5-pKxIeCQdtumi3F0Ld7J4&s=-QFdY9fjmu7_2rmXlcIXfJrDj4Qwl85njBy2y2vrSmY&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 

[image: COB_B_Blue_square-01.png]

David Upton

Digital Team / Operations Team

Department of Innovation and Technology

781 330 5041 (c)

**Comment by stephaniemar** [comment]
@davidrkupton @duffy-james Has this been completed?

**Comment by duffy-james** [comment]
Yup, this is resolved.
