### ISSUE TITLE
Group Management not working as expected

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#884]
Gretchen (102214) goes into Group Management and searches for groups she can manage (FHESALESFORCE, I'm in the SG_AB_GRPMGMT_FHESALESFORCE group).  No results found.  I think the groups I manage should be listed.
![Screenshot 2022-03-23 083242](https://user-images.githubusercontent.com/91092683/159702715-e7a039bc-5fb0-4369-9bdb-0142678095a9.png)
Phil C had same issue last week and some sort of tweak was done to fix it.  Not sure if also done for Rashad D (133406) who had similar experience.  Would like to find root cause and address (not have individuals complaining as they discover this!)

**Comment by rachelsater** [comment]
@g-grozier Hi, is this the priority over the Identity work Phil is currently doing?

**Comment by g-grozier** [comment]
This is a production issue - so yes, it's the priority.

**Comment by rachelsater** [comment]
Ok thanks! Phil will start looking into this today and will get back to you with any questions. Also, this will potentially push back the Identity work.

**Comment by g-grozier** [comment]
Given we've been waiting for 4 months a few hours won't matter.

**Comment by rachelsater** [comment]
fab!

Can you please add Phil to the Group test and prod environments so he can triage?

**Comment by phillipbentonkelly** [comment]
My account IDs
TEST Env: 40000093
PROD Env: 40001390

**Comment by g-grozier** [comment]
he's the developer of those environments.  He is already in them?

**Comment by phillipbentonkelly** [comment]
I am not in that group, I can't just give myself access them.

Those accounts below:

PROD
![image](https://user-images.githubusercontent.com/2627273/159730256-c1472960-6fdb-4c57-b95b-ef35bceca911.png)

TEST
![image](https://user-images.githubusercontent.com/2627273/159730515-0a952446-ea08-4e7d-8b93-4bab9e639026.png)

I need to be added to these on PROD and TEST so I can test better by myself ... you can take me off after
- SG_AB_FHESALESFORCE
- SG_AB_GRPMGMT_FHESALESFORCE

**Comment by g-grozier** [comment]
We can put you into some group management groups in TEST if that is helpful.
I'd prefer you work there - but can you check the users who are having
issues and see why it's not working for them?




[image: COB_B_Blue_square-01.png]

*Gretchen Grozier *(pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by phillipbentonkelly** [comment]
Which users are these (IDs)? and what was the change you did to Phil C account

**Comment by g-grozier** [comment]
the 2 people who are having the issue are in the ticket opening statement
(Rashad and I) - at least, that is who I know of.
I'm assuming other app owners would say if it wasn't working for them...but
that is a big assumption.

I don't know what was done for Phil C -- David said he updated the ticket
(in TrackIT)

**Comment by phillipbentonkelly** [comment]
@g-grozier 

OK, we don't have access to TrackIt, would you be able to share what it says?

I took at look at PROD & TEST

- Rashad is missing both `SG_AB_FHESALESFORCE` and `SG_AB_GRPMGMT_FHESALESFORCE` groups in PROD and TEST
![image](https://user-images.githubusercontent.com/2627273/159765318-dd25660d-3e02-46d4-a84b-3dfafe1ab3b4.png) 
![image](https://user-images.githubusercontent.com/2627273/159765416-934e138b-8913-4a23-8323-4105bb60aac1.png)
- Gretchen you have `SG_AB_GRPMGMT_FHESALESFORCE` in PROD but are missing `SG_AB_FHESALESFORCE`; 
![image](https://user-images.githubusercontent.com/2627273/159764863-aa07d6a0-4fe1-4254-97a9-d5ed67395f15.png) 
  in TEST you are missing both 
![image](https://user-images.githubusercontent.com/2627273/159765075-5475bd15-dd73-42ef-a3ae-bbc43dccf143.png)
 ... you should have your accounts updated with the missing groups on those environments and try again

In the app, `Group Search` only returns groups you have access to or can manage ... so if you're not in them it won't return anything

**Comment by g-grozier** [comment]
@davidrkupton told me he updated the TrackIT - so he should be able to tell you what he wrote.
I am in the SG_AB_GRPMGMT_FHESALESFORCE group in Prod and that is where I need to work and where I am reporting the issue

**Comment by davidrkupton** [comment]
> @davidrkupton told me he updated the TrackIT - so he should be able to tell you what he wrote. I am in the SG_AB_GRPMGMT_FHESALESFORCE group in Prod and that is where I need to work and where I am reporting the issue

I dont have access to trackit either, no-one at all in Digital does, in I was talking about our tickets in Github, principally this ticket.

**Comment by g-grozier** [comment]
Peter put me in the SG_AB_SALESFORCE group and after LDAP sync, I can see it in my Group Management area.

**Comment by davidrkupton** [comment]
This issue has been transferred to #601
