### ISSUE TITLE
Access Boston Registration bug

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#888]
When a user sets up MFA they can choose to use email for their second factor (but it's a wee link at the bottom to discourage them).  If they do choose to use email -- the system is supposed to check against the City's domains and NOT let them register using an City email (bpl.org, boston.gov, etc).  

I'm looking at users who have enrolled for PingID with email as their primary second factor and all the Boston domains are in there....which if they are trying to use forgot password to get a code is going to be SUPER HARD to get.  One of the tabs on [Portal Content Google Sheet](https://docs.google.com/spreadsheets/d/1OiH2HBLE55X8MzGaB7H9VC_a2WpQQcjV4-eyNpJGTPY/edit#gid=1222457676) is the list of domains to be embargoed.   

Need this fixed asap...please

**Comment by g-grozier** [comment]
specifically found bpl.org, boston.gov and bostonpublicschools.org in the registered email addresses

**Comment by davidrkupton** [comment]
The blacklist is as follows (from the portal in the first comment):
- boston.gov
- pd.boston.gov
- bostonpublicschools.org
- bpl.org
- cityofboston.gov
- ci.boston.ma.us
- boston.k12.ma.us
- bphc.org

**Comment by g-grozier** [comment]
I just added *bphc.org <http://bphc.org>* to the list (on the Sheet).  We
are in the process of integrating with the Public Health Commission so as
long as we are in there, let's just add them now.

**Comment by phillipbentonkelly** [comment]
Est. 3hr

@g-grozier I am going to need to work with someone on your team to integrate and test this; that will require at least an hour meeting tomorrow or Friday. Last time I worked with Navan but you let know who's available that knows about this on your team and invite them. Also, they'll need to have a couple of accounts ready to test with.

cc: @davidrkupton, @rachelsater

**Comment by davidrkupton** [comment]
@g-grozier 
We have found this code in the main Access Boston application.
We can add validation to the email address before it is submitted to Ping/FID to check the email address is not on the domains listed above.
In order to test, could we have 3 usernames and passwords for accounts that are in the "Needs Registration" status on the Test environment.

**Comment by phillipbentonkelly** [comment]
@g-grozier, am picking up on this request again, trying to remember/confirm some details ... is this the page were applying this modification too?

https://access-test.boston.gov/storybook/?path=/story/registermfapage--email
![image](https://user-images.githubusercontent.com/2627273/174153017-cc0bf09a-501b-4af4-afcc-ee6d6c8cfe9e.png)

CC'd @stephaniemar so she's aware of the storybook templates for these pages, etc

**Comment by ggrozierBOS** [comment]
@phillipbentonkelly yes, should someone type in email address there we need to return error if it's a City of Boston associated domain (one of the ones listed above).  @stephaniemar let me know if you need more details

**Comment by stephaniemar** [comment]
Ok. Thanks @g-grozier --seems pretty straight forward.

**Comment by phillipbentonkelly** [comment]
@ggrozierBOS I deployed the change to both DEV/TEST

In order to test, could we have 3 usernames and passwords for accounts that are in the "Needs Registration" status on the DEV or Test environments.

**Comment by DineshBaddam** [comment]
Hi Phill
These are the Test user account you can try.
Test Users 
167525
Downtown341$
167512
Puzzle950$
167528
Rustic996#

**Comment by phillipbentonkelly** [comment]
Hi @DineshBaddam, the logins are not working, could they have expired by any chance ... also Are these for the DEV or TEST environment

**Comment by DineshBaddam** [comment]
Hi Phill,

Here are the Test Users in Test Environment
167525
February102$
167512
United729$
167528
Winter517$

Thanks,
Dinesh.

**Comment by phillipbentonkelly** [comment]
@ggrozierBOS, @stephaniemar domain exclusion is verified on the TEST environment.

**Comment by stephaniemar** [comment]
Thanks @phillipbentonkelly  @g-grozier Is this something we will need a Change Management form to deploy to PROD?

**Comment by ggrozierBOS** [comment]
I don't think it needs a change, but we will be doing testing too.   Will
let you know the results!  G.

**Comment by ggrozierBOS** [comment]
Tested will all the domains and not one of them would go through!

![Image](https://user-images.githubusercontent.com/104460350/175615774-5a37a2bc-ab43-4694-8d0d-ed54eb323816.jpg)
![Image](https://user-images.githubusercontent.com/104460350/175615773-522fa842-a950-4a23-b124-7c00e10ee0a3.jpg)
![Image](https://user-images.githubusercontent.com/104460350/175615772-dc785f62-26ce-4a10-a37a-b51be623f3a9.jpg)
![Image](https://user-images.githubusercontent.com/104460350/175615776-e7fc3486-5b06-4f64-999b-bd1464c4e013.jpg)
![Image](https://user-images.githubusercontent.com/104460350/175615775-fe31e676-0e40-456c-850d-5de39fb0aa30.jpg)

**Comment by stephaniemar** [comment]
Great!

**Comment by DineshBaddam** [comment]
I have also validated the senario with all email endings, which is not accepting the work emails.

Thanks,
Dinesh.

**Comment by phillipbentonkelly** [comment]
Deployed to PROD

**Comment by ggrozierBOS** [comment]
We are good to send this to Prod!
