### ISSUE TITLE
Access Boston Banner Pre-BAIS Mod Cutover

### ISSUE THREAD

**Issue by g-grozier** [CityOfBoston/digital#889]
Add a banner to the Access Boston Portal on 4/28 stating:
Notice: BAIS cutover scheduled for 5/19 to 5/22. The HCM, FN and ESS applications will not be available.

(this is Gretchen's text still need to confirm with BAIS folks!)

**Comment by stephaniemar** [comment]
@phillipbentonkelly @davidrkupton -- For these types of requests do you want to have separate tickets for updating test and PROD? We can have one ticket that has all the info you need to update the test environment for testing then a separate ticket specifically for deploying to PROD with specific dates. 
Let me know what you think works best and I can update and add the tickets.

**Comment by phillipbentonkelly** [comment]
Usually we would prefer separate tickets but this is simple enough for one if remember we need to check on both environments.

**Comment by stephaniemar** [comment]
Ok. I will write out all the steps for each ticket so we know exactly what to do.

**Comment by stephaniemar** [comment]
We will be adding a banner to ABP for the BAIS Mod Cutover to alert users IAM systems will be unavailable.

- [ ] Date needed on PROD: 4/28/2022 - 5/22
- [ ] Applications unavailable: HCM, FN, ESS
- [ ] Message for Banner: BAIS cutover is scheduled for 5/19 to 5/22. The BAIS HCM, BAIS FN and Employee Self-Service applications will not be available
- [ ] Add this banner to test 4/26? 
- [ ] Deploy to Prod 4/28
- [ ] Remove from Prod 5/22

@g-grozier -- can you confirm the banner message?

**Comment by ggrozierBOS** [comment]
PLEASE NOTE: BAIS cutover is scheduled for May 19 - 22. The BAIS HCM, BAIS FN, and Employee Self-Service (ESS) applications will not be available during that time.

**Comment by stephaniemar** [comment]
@phillipbentonkelly We have final approval on the banner on TEST - We can deploy this to PROD at the end of the day today so it is there tomorrow morning. 

cc @g-grozier @davidrkupton
