### ISSUE TITLE
Update Careers Center URL in PROD 6/30

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#902]
Update Career Centers URL in PROD 5/26 to the following: https://sso.boston.gov/idp/startSSO.ping?PartnerSpId=icims.com&TargetResource=https%3A//employeeconnect-boston.icims.com/r.jsp

**Comment by stephaniemar** [comment]
@ggrozierBOS - What is the timing for this on 5/13? Should we update the night before or on the morning of 5/13?

**Comment by ggrozierBOS** [comment]
please disregard last comment which was for Avolve...which you all do not
need to do.   But we are doing an end of day deploy for Career Center too.
So Phill can start at 3 ....so it's live at 5 I think.  G.

**Comment by stephaniemar** [comment]
@phillipbentonkelly is this done?

**Comment by ggrozierBOS** [comment]
@phillipbentonkelly and @stephaniemar this Change got moved due to a bug on vendor side.  They are fixing it in their June release ("at the end of the month") so I moved our CR to 6/30

**Comment by stephaniemar** [comment]
@ggrozierBOS @phillipbentonkelly I will update the target date.

**Comment by stephaniemar** [comment]
@ggrozierBOS Is this still a go for tomorrow? Is there a timeline?

**Comment by ggrozierBOS** [comment]
Yes, we will push code (well change configs) at 5pm tomorrow.   G.


Gretchen Grozier (pronouns: she/her/hers)

Director of Identity & Access Management

Department of Innovation & Technology

617-635-3547 (w), 617-388-5317 (c)

**Comment by stephaniemar** [comment]
We were informed we do not have to do this work. Closing it out.

**Comment by ggrozierBOS** [comment]
Sorry, I think I did not reply.  This should happen at the end of the day
on 5/13.  IAM plans to deploy in Ping Prod about 5...I can add you all to
the Change Req (if you want)
They are "going live" on Monday May 16th -- but want staff to use it once
they arrive.  G.
