### ISSUE TITLE
Update URLs for HCM, FN and Phire for BAIS cutover (PROD)

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#905]
Update URLs for HCM and FN tiles on ABP for BAIS Mod cutover - This has been updated 5/17

- [x] ~~Please add the following links on ABP TEST to the FN and HCM Tiles for testing on Tuesday 5/17
FN--->>>https://fn.boston.gov/
HCM--->>>https://hcm.boston.gov/~~

We were hoping to go with the short URLS but that will not work so please use URLs below  
- [x] Please deploy the following URLs PROD on Friday 5/20 -- Updated with correct URLs 5/22
FN ----> https://fn.boston.gov/psp/psfnprd/EMPLOYEE/ERP/h/?tab=DEFAULT
HCM----> https://hcm.boston.gov/psp/pshrprd/EMPLOYEE/HRMS/h/?tab=DEFAULT
PHIRE---->https://phireprd.bais.boston.gov/psp/phire/EMPLOYEE/PT_LOCAL/h/?tab=DEFAULT

- [x] Please revert FN and HCM TEST URLS  Monday AM 5/23

@ggrozierBOS @davidrkupton

**Comment by stephaniemar** [comment]
Hi @ggrozierBOS Phil has updated TEST- You can have whoever test it to make sure it looks ok. If it does then @phillipbentonkelly can deploy to Prod on Friday.

**Comment by stephaniemar** [comment]
@phillipbentonkelly - Just a reminder to revert FN and HCM Test URLs, I think this still needs to be done. Thanks!

**Comment by phillipbentonkelly** [comment]
Reset

**Comment by stephaniemar** [comment]
@ggrozierBOS do you have a way to make sure the test URLs are working again?

**Comment by ggrozierBOS** [comment]
Yes, both tiles are on my Test ABP and both are working as expected.
Thanks!!

**Comment by stephaniemar** [comment]
Great I will close.
