### ISSUE TITLE
Group Management URL Security Fix

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#907]
Jira: https://github.com/CityOfBoston/digital/issues/907

This is a fix to ensure that users cannot go directly to the Group Management by entering the URL directly into the browser.
- This will ensure we do not have an issue with the group mgmt service on ABP

**Comment by davidrkupton** [comment]
This addresses a small security issue.
Users (who have already successfully logged into Access Boston), and who would not normally be allowed to access the `Group Management` utility, could still access the utility by typing its URL directly into the browser.
This would not allow them to do anything they are not authorized to do.
We feel that if they are not authorized to see the link, then they should not be able to access the page and want to update the backend code to check permissions as the page is loaded and redirect to the AB homepage if the user is not authorized to see the page.
Simultaneously we will also streamline the group-management group scanner, reducing the number of API calls made to the LDAP server speeding up the utility and reducing load on the back-end servers.

**Comment by davidrkupton** [comment]
Est time: 1 week to develop, test and deploy
Impact to Service: no production impact.
