### ISSUE TITLE
Make email option less obvious (Register MFA Page)

### ISSUE THREAD

**Issue by rachelbraun** [CityOfBoston/digital#91]
IAM would like to encourage users to use Phone MFA over Email. Let's make the Email option less obvious to users visually.

Here's what we're currently doing:
<img width="496" alt="screen shot 2018-10-10 at 4 00 14 pm" src="https://user-images.githubusercontent.com/35377030/46763068-d8477800-cca6-11e8-9686-8b42704f46a6.png">

Here's a visual option they liked (as seen on the RegisterMfaPage > DeviceVerificaitonModal > incorrect code preview):
<img width="438" alt="screen shot 2018-10-10 at 4 06 19 pm" src="https://user-images.githubusercontent.com/35377030/46763077-dda4c280-cca6-11e8-967b-e2da8659ab5c.png">

**Comment by fionawhim** [comment]
Removing assignee since this is still in the Backlog.

**Comment by fionawhim** [comment]
OK, updated to make links that take the user between the states. (Back / forward buttons work after clicking the links)


<img width="993" alt="screen shot 2019-01-25 at 1 58 21 pm" src="https://user-images.githubusercontent.com/260837/51766762-62c2b480-20a9-11e9-851e-affb1e5f6b0b.png">

<img width="993" alt="screen shot 2019-01-25 at 1 58 25 pm" src="https://user-images.githubusercontent.com/260837/51766774-6b1aef80-20a9-11e9-9ffc-4ab99ef39bb6.png">

**Comment by fionawhim** [comment]
Implemented in #266, just waiting on @rachelbraun / IAM team review of UI.

**Comment by rachelbraun** [comment]
Looks great.

Passed on to IAM and Greg for review. Will advise.

**Comment by rachelbraun** [comment]
They said it looks great. Good to go.
