### ISSUE TITLE
View Only Group Management

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#912]
JIra: https://bostondoit.atlassian.net/browse/DIG-10

Phill and David -- this is new request form Access Boston that we can review. 

**Issue:** DoIT Service Desk would like access to Group Management (view data only) to perform searching by person and view a person's group management associations. The support team was given access to Netscaler  during the pandemic which gave them access to group management  searches for VPN support. It was decided to take away this access so they did not mistakenly change a users profile in group management. This was a helpful tool to triage ABP Support issues. 

**Requirements**
- This will allow the support staff to assist end users with their ABP group management security questions
- The support staff would have the group management link on ABP but when clicked will only see the search by person option
- Search results will be view only, support staff will have no edit abilities
- Support users who should have this view belong to the following security group: SG_AB_SERVICEDESK_USERS
- If doable we can possibly offer this to the other IT support staff

**Screen Shots** 
Group Management on ABP

![Image](https://user-images.githubusercontent.com/92751818/170113870-bda670c0-a4a2-468d-a876-142c96caae4b.png)

Support View 

![Image](https://user-images.githubusercontent.com/92751818/170113984-b1378b2d-2ffb-4fa1-a37e-14d95cd88486.png)

Group list should be view only 

![Image](https://user-images.githubusercontent.com/92751818/170114449-d947846a-0e4c-4c51-9b00-de378d1c3539.png)
- We probably do not need Review Changes button 

**Priority:**
- Low- to medium 
- Nice to have 
- It is always nice to support the Service Desk since they support all of us

**Comment by phillipbentonkelly** [comment]
Of the top of my head I believe this would take 4-5 days; there is no concept of view only and you can get to groups from viewing the user so I would have to close those doors, etc

**Comment by stephaniemar** [comment]
Ok Thanks @phillipbentonkelly
