### ISSUE TITLE
Update to Forgot Password

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#915]
On the Forgot Password page -- we say UserName....can we make sure it will allow the entry of either the User ID or the User's email address (which is how the Login Page works). 

Is Portal doing any sort of data validation on that field (checking for a 6 or 8 digit number)?  If yes, change to also check for well-formed email address.  If not, then Digital has no work to do (IAM has to make sure IIQ can handle it on our side!)

![Image](https://user-images.githubusercontent.com/104460350/171191473-baba3a16-9df4-4e63-8854-6c856030cbb9.jpg)

**Comment by stephaniemar** [comment]
Hey @phillipbentonkelly can you answer Gretchen's initial question about if that username field in the forgot password workflow doing any data validation? Will it accept an employee ID or email? We may not have any work here.

**Comment by phillipbentonkelly** [comment]
It only validates to make sure its not empty

**Comment by stephaniemar** [comment]
So it sounds like we do not have any work here?

**Comment by phillipbentonkelly** [comment]
We would have to change the label for them to say username or email ...

**Comment by stephaniemar** [comment]
It only says username on the APB login screen so we can stay consistent with that.
