### ISSUE TITLE
Update group that see 'Building Maintenance' link

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#916]
Currently in the **Forms/Links** section of the Access Boston Portal we show the _Building Maintenance_ link to any user with 'cobuseragency' = CH.   Property Management asked us to also add in the group 'cobuseragency' = Assessing too.

**Comment by stephaniemar** [comment]
Please add 'cobuseragency' = Assessing to show the Building Maintenance link to people in that group under the Forms/Links section of Access Boston Portal. 

@phillipbentonkelly let me know if you have questions about this?

**Comment by phillipbentonkelly** [comment]
Changing this can be done over a couple or hours

- Is `Assessing` the correct(tly formatted) value for this agency? Asking because every other `agency` value we have in the configs are made up of 2-3 capitalize letters.
- Is this work on going to be tested on `DEV and TEST` or just `TEST`
- Is there a ticket for the deploy to PROD with a target date?

**Comment by ggrozierBOS** [comment]
@phillipbentonkelly 

- Yes the value for Assessing Staff in cobUserAgency is ASSESSING

![Tuyen](https://user-images.githubusercontent.com/104460350/171909105-d0fd678e-57fd-4715-b5c3-32776b7c18ec.jpg)

- We should do this in Dev, then Test and then Prod.
- No change request in for Prod yet...needed to know timings, etc.

**Comment by stephaniemar** [comment]
@phillipbentonkelly See Gretchen's Answers above.

**Comment by phillipbentonkelly** [comment]
I'll deploy to DEV today

**Comment by stephaniemar** [comment]
Ok. sounds good then we can make a plan moving forward.

**Comment by phillipbentonkelly** [comment]
deploy done

**Comment by stephaniemar** [comment]
@ggrozierBOS Phil has this on Dev, is this something you can test?

**Comment by ggrozierBOS** [comment]
I will ask one of the QA folks on my team to do that....I don't know a
login in DEV for an Assessing user (and don't have access to update
accounts there).


Gretchen Grozier (pronouns: she/her/hers)

**Comment by ggrozierBOS** [comment]
we don't have any folks in the Dev environment who have Asseessing in that field, can we move on to TEST environment (where we can actually test it) pls? @phillipbentonkelly

**Comment by phillipbentonkelly** [comment]
I can update it after 2pm

**Comment by ggrozierBOS** [comment]
that is great - thanks!

**Comment by phillipbentonkelly** [comment]
The services restarted, you can check TEST

**Comment by ggrozierBOS** [comment]
Both Dinesh and I checked in TEST with 052509 and 116193 in Test environment instead (super secret password of Boston@2022).  They see the new link.  Good to go to Prod @phillipbentonkelly

**Comment by stephaniemar** [comment]
@phillipbentonkelly Gretchen and I talked yesterday, we do not need to a CM For this. You can deploy to PROD.
Thanks!

**Comment by stephaniemar** [comment]
Hey @phillipbentonkelly I know you are working on another ticket right now, but can this get done today before you leave on vacation?

**Comment by phillipbentonkelly** [comment]
I'll deploy it now

**Comment by stephaniemar** [comment]
This is complete.
