### ISSUE TITLE
View User Info - integrate workgroup to provide this link

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/digital#918]
Jira- https://bostondoit.atlassian.net/browse/DIG-54

We have a workgroup called: COB-Workgroup-ViewIdentityOnly

I don't think we actually ever built this into the Access Boston Portal though....

For users in this workgroup we need to display **'Support Tools'** section and then provide them with the _View User Information_ link there.  

Would be good to have this function in place for BPHC IT Support users (6/16)

**Comment by stephaniemar** [comment]
@ggrozierBOS - Just so I understand the ask. When you say the work group COB-Workgroup-ViewIdentityOnly was never build into ABP, do you mean we have the group but it not used? or, we have it and we just need to give everyone in this group the View User Information link?

**Comment by ggrozierBOS** [comment]
we have the group in IAM systems but the integration so ABP reads it and
reacts to populate the right things isn't there...

**Comment by stephaniemar** [comment]
Hey @phillipbentonkelly do you understand the ask here? Can you give an estimate for the work.

**Comment by phillipbentonkelly** [comment]
This reads as add a new link under that section with a that group. If that's all it is then it fine, just need the deploy details ... dev/test/prod, title, link, group (properly cased)

**Comment by stephaniemar** [comment]
@ggrozierBOS See Phill's comments. Just need some info for testing and we can prioritize.

**Comment by ggrozierBOS** [comment]
The link exists already (as part of the Support Tools package that those in Help Desk group get).
For this one, look for IIQ_ViewIdentity group in FID and populate the **Support Tools** section on ABP with the _View User Information_ link only. @stephaniemar  @phillipbentonkelly

**Comment by phillipbentonkelly** [comment]
@ggrozierBOS 

Is `IIQ_ViewIdentity` the correct/capitalize spelling for this group? I'll start today by deploy it to `DEV` environment first, since we haven't specified what environment we it will be tested first.

**Comment by ggrozierBOS** [comment]
That is what I see in TEST and PROD....I don't know if it is in DEV (no
view into that FID environment).  But I gotta think it is...

**Comment by phillipbentonkelly** [comment]
@ggrozierBOS what about the group name question above, is `IIQ_ViewIdentity` the correct capitalization/spelling?

**Comment by ggrozierBOS** [comment]
I just said yes, that is the group I see in TEST and PROD...

**Comment by phillipbentonkelly** [comment]
@ggrozierBOS I misunderstood your response, 

Added that group to the `View User Info`  tile, now those in that group will see that link under `Support Tools`. DEV/TEST are updated and deployed.

**Comment by stephaniemar** [comment]
Hey just catching up on this---  @ggrozierBOS, were you able to take a look at what @phillipbentonkelly deployed on DEV/TEST? 
Thanks,
Steph

**Comment by ggrozierBOS** [comment]
Yes, @stephaniemar I just met with IAM team because there seems to be a disconnect between IIQ and FID (and naming changes between environments). They are working on getting that all sorted out...so we can test what @phillipbentonkelly has done

**Comment by stephaniemar** [comment]
@ggrozierBOS Great. Just let us know when you are done.

**Comment by stephaniemar** [comment]
@ggrozierBOS How is the testing going? Need anything?

**Comment by ggrozierBOS** [comment]
@phillipbentonkelly Navan set up the groups correctly now in FID...it is called **SG_AB_IIQ_ViewIdentity**

**Comment by ggrozierBOS** [comment]
I've asked @Dinesh Baddam ***@***.***> to test this
today...I'll try to chime in as time allows

**Comment by phillipbentonkelly** [comment]
Updated tiles in DEV/TEST with the correct group name (from above)

**Comment by stephaniemar** [comment]
@phillipbentonkelly thanks! I think this means you are free to test now @ggrozierBOS

**Comment by DineshBaddam** [comment]
Hi Phill,
I don't see the View User Info link in Test Access Boston(075715)

![image](https://user-images.githubusercontent.com/39305170/175354234-b2049538-8ed8-426a-918a-0579b08036f8.png)
In SAML Tracer I see the Attribute

![image](https://user-images.githubusercontent.com/39305170/175354459-549f63f2-6226-4749-b770-cbfd7ecb54be.png)

Here are the Group Details

![image](https://user-images.githubusercontent.com/39305170/175354944-85b8228d-e0de-461e-bb1e-07c8d70ca142.png)

**Comment by phillipbentonkelly** [comment]
Try again now

**Comment by ggrozierBOS** [comment]
Yahtzee.  (well I see it on my Portal anyway).  Will ask Dinesh to try with
others we set up

**Comment by DineshBaddam** [comment]
I see it now, Thank you.
![image](https://user-images.githubusercontent.com/39305170/175364707-8d39c885-d640-4af2-b190-14b6e0939b00.png)

**Comment by ggrozierBOS** [comment]
this is good to move to Prod at any convenient time! @Stephanie Cariello
***@***.***> says she will do the Change Request

**Comment by phillipbentonkelly** [comment]
Deployed to PROD

**Comment by stephaniemar** [comment]
This is complete.
